### ISSUE TITLE
Error Trait 'Laravel\Cashier\Billable' not found

### ISSUE THREAD

**Issue by lmatab** [laravel/cashier-paddle#1]
- Cashier Paddle Version: v.1.0.0-beta
- Laravel Version: 7.13.0
- PHP Version: 7.4
- Database Driver & Version: Mysql

### Description:
After following the steps in the docs I get this error:
```
Trait 'Laravel\Cashier\Billable' not found
````
### Steps To Reproduce:

$user = App\User::find(1);
$payLink = $user->newSubscription('default', 'premium')
    ->returnTo(route('home'))
    ->create();

**Comment by lmatab** [comment]
I have made this change to make it work:

```
use Laravel\Cashier\Billable;
```
 for 

```
use Laravel\Paddle\Billable;
```
in the App\User model and it works now, maybe a typo in the docs.

**Comment by akiyamaSM** [comment]
@lmatab Thats correct.

**Comment by driesvints** [comment]
Hey thanks. I already updated the incorrect docs. Thanks for testing!

**Comment by saber13812002** [comment]
in my case installation didnt complete 

my error is Memory limit 

i can fix it by add memory_limit =-1 in php.ini
this solve my issue.

**Comment by driesvints** [comment]
@saber13812002 seems to be a general Composer issue since a few weeks.

**Comment by enkota** [comment]
> @saber13812002 seems to be a general Composer issue since a few weeks.

Was getting a similar problem with another package running out of memory. Fixed it with the `-1` memory limit config.

**Comment by nomanshaikh17** [comment]
> I have made this change to make it work:
> 
> ```
> use Laravel\Cashier\Billable;
> ```
> 
> for
> 
> ```
> use Laravel\Paddle\Billable;
> ```
> 
> in the App\User model and it works now, maybe a typo in the docs.

thats very helpfull and solve my problem
