### ISSUE TITLE
Paypal: expiry_date and last_four_digits not available

### ISSUE THREAD

**Issue by SebastianSchoeps** [laravel/cashier-paddle#104]
- Cashier Paddle Version: 1.4.1
- Laravel Version: 8.28.0
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 8

### Description:
Using the new Spark. After connecting to Paypal (German account) I receive a 500. It originates in `Subscription.php`: 
`Undefined array key "expiry_date"` (and afterwards the same for `last_four_digits`).

`paddleInfo` returns:
```
array (
  'subscription_id' => 625...,
  'plan_id' => 6451...,
  'user_id' => 204...,
  'user_email' => 'seba...@...uc.com',
  'marketing_consent' => false,
  'update_url' => 'https://checkout.paddle.com/subscription/update?user=204...&subscription=625...',
  'cancel_url' => 'https://checkout.paddle.com/subscription/cancel?user=204...&subscription=625...',
  'state' => 'active',
  'signup_date' => '2021-02-16 16:52:15',
  'last_payment' => 
  array (
    'amount' => 0,
    'currency' => 'USD',
    'date' => '2021-02-16',
  ),
  'linked_subscriptions' => 
  array (
  ),
  'payment_information' => 
  array (
    'payment_method' => 'paypal',
  ),
  'next_payment' => 
  array (
    'amount' => 0,
    'currency' => 'USD',
    'date' => '2021-03-16',
  ),
)  
```

There is no array key `['payment_information']['expiry_date']`.

Just FYI I applied a 100% coupon.

### Steps To Reproduce:
Connect to PayPal.

`Arr::get()` solves the problem - I'm just curious why this seems to be only me? Many others should run into this too.

**Comment by driesvints** [comment]
This is already fixed in Spark. I'll PR a change to cashier in a sec. You can already first check if you're using paypal or a card with calling `->paymentMethod()`
