### ISSUE TITLE
Paddle Checkout - Function name must be a string

### ISSUE THREAD

**Issue by Hussam3bd** [laravel/cashier-paddle#11]
- Cashier Paddle Version: 1.0@beta

```
Function name must be a string (View: /vendor/laravel/cashier-paddle/resources/views/components/checkout.blade.php)
```
https://share.getcloudapp.com/YEup1Xrv

I think the `()` in `$options()` added by mistake or sth?

**Comment by driesvints** [comment]
Hmm no that should perfectly work. Can you share how you're using the checkout component?

**Comment by Hussam3bd** [comment]
Hi @driesvints 

PHP Version: 7.4.2
Laravel Version: 7.3.0

Here how I'm using it.

```
$payLink = auth()->user()
            ->newSubscription('default', $premium = 596743)
            ->returnTo(route('dashboard.index'))
            ->create();
```

```
<x-paddle-checkout :override="$payLink" class="w-full"/>
```

Even when I try to pass options to the checkout component:

```
<x-paddle-checkout :override="$payLink" class="w-full" :options="['locale' => 'ar']"/>
```
I get the same error

```
Function name must be a string (View: /vendor/laravel/cashier-paddle/resources/views/components/checkout.blade.php)
```

**Comment by driesvints** [comment]
That's super odd. I can use it just fine: 
![Screenshot 2020-06-19 at 11 40 35](https://user-images.githubusercontent.com/594614/85119237-bc3cfd80-b221-11ea-9605-3ab6dd432ac6.png)

**Comment by driesvints** [comment]
Does upgrading to the latest laravel version fixes the problem for you?

**Comment by driesvints** [comment]
Make sure to clear your view cache after that.

**Comment by Hussam3bd** [comment]
@driesvints yeah thank you that solved the problem!
