### ISSUE TITLE
Subsription model scopes bug

### ISSUE THREAD

**Issue by monoteos** [laravel/cashier-paddle#110]
- Cashier Paddle Version: v1.4.3
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:
```
/**
     * Determine if the subscription is active.
     *
     * @return bool
     */
    public function active()
    {
        return (is_null($this->ends_at) || $this->onGracePeriod() || $this->onPausedGracePeriod()) &&
            (! Cashier::$deactivatePastDue || $this->paddle_status !== self::STATUS_PAST_DUE) &&
            $this->paddle_status !== self::STATUS_PAUSED;
    }

    /**
     * Filter query by active.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return void
     */
    public function scopeActive($query)
    {
        $query->where(function ($query) {
            $query->whereNull('ends_at')
                ->orWhere(function ($query) {
                    $query->onGracePeriod();
                })
                ->orWhere(function ($query) {
                    $query->onPausedGracePeriod();
                });
        })->where('paddle_status', '!=', self::STATUS_PAUSED);

        if (Cashier::$deactivatePastDue) {
            $query->where('paddle_status', '!=', self::STATUS_PAST_DUE);
        }
       // missed return statement here <----
    }

```

You missed **return** statement in all scopes in Subscription model (maybe other models, didn't check)

Example, Laravel scope

```
/**
     * Scope a query to only include active users.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('active', 1);
    }
```

Also you override scope "scopeActive" by "active" function in the same model, is it expected?

Thanks,
Konstantin
Massive Kinetic

**Comment by yoeriboven** [comment]
I don't think you are required to return anything in local scopes.

Are these functions not working for you or do you *think* it doesn't work?

Also, `scopeActive` and `active` are used in different ways so there is no override situation.

**Comment by driesvints** [comment]
Hi there. It's indeed not necessary to return the query builder. Eloquent is smart enough to handle this.

> Also you override scope "scopeActive" by "active" function in the same model, is it expected?

Yeah it is. Please see how to use Cashier scopes here: https://laravel.com/docs/8.x/cashier-paddle#subscription-scopes
