### ISSUE TITLE
To be able to get all the subscriptions + users associated with them

### ISSUE THREAD

**Issue by Benoit1980** [laravel/cashier-paddle#111]
Hello,

I have noticed that there is no possibility to run this query:
```
$todaysDate = Carbon::now()->format('Y-m-d');
$failedPayments = Subscription::whereDate('ends_at', '<', $todaysDate)->with('users')->get();
```

Will you ever add a relation between the users and the subscriptions please in your subscription model?

Thank you.

**Comment by driesvints** [comment]
No because that'd be a circular dependency. 

Maybe https://laravel.com/docs/8.x/eloquent-relationships#nested-eager-loading-morphto-relationships is what you're looking for?

**Comment by Benoit1980** [comment]
Thanks, I will try that :-)
