### ISSUE TITLE
Sandbox switch

### ISSUE THREAD

**Issue by Benoit1980** [laravel/cashier-paddle#115]
Hi,

Based on your DOC
https://laravel.com/docs/8.x/cashier-paddle#paddle-sandbox

I cannot see a way to switch blade from:
@paddleJS

To something like:
@paddleJS-sandbox

Will you ever add some kind of switch or are we forced for now to replace manually the header URL by adding a new ENV variable ie: Paddle-sandbox: true / false

Thank you.

**Comment by Benoit1980** [comment]
ok forget it, just noticed the PADDLE_SANDBOX ENV variable.

**Comment by Tiththa** [comment]
For anyone referring, set `PADDLE_SANDBOX=true` in ENV if testing in sandbox
