### ISSUE TITLE
Multiple WebHooks possibility

### ISSUE THREAD

**Issue by Benoit1980** [laravel/cashier-paddle#116]
Hi,

To my surprise, I wanted to use your script on a second domain and realised that Paddle does not have a way to set up multiple webhook ULRS in their admin panel. So if you have this script setup on 2 domains, only 1 webhook URL can be set.

It would have been great to have the possibility to setup a webhook redirection from 1 installation/domain to another using your package as this seems to be a big problem with Paddle.

Thank you.

**Comment by mpociot** [comment]
I think this is an issue that should be reported to Paddle than on this package 🙂

**Comment by driesvints** [comment]
Please contact Paddle as we can't control what features Paddle provides.

**Comment by Benoit1980** [comment]
Yes I did already, but they have nothing to fix the problem. You either have to pay Zappier to have it working or build your own solution. I thought it would have been a great little add-on to your package. But if you think it is not worth it, no worry :-) I found a lot of posts about this particular issue on the net, it seems to bother people a lot.
