### ISSUE TITLE
Display prices after a coupon reduction not working

### ISSUE THREAD

**Issue by Baspa** [laravel/cashier-paddle#117]
- Cashier Paddle Version: 1.2
- Laravel Version: 7.0
- PHP Version: 7.4.16

### Description:
I created a coupon code with a 50% discount in Paddle. As described in the [docs ](https://laravel.com/docs/7.x/cashier-paddle#prices) I wanted to display the new prices with the coupon code applied. I used the code from the documentation like this:

`$plans = Cashier::productPrices([647422, 647406], ['coupons' => '50PERCENTOFF']);`

However, this still shows me the exact same prices as it was before applying the coupon. As far as I can see it looks like the coupon code isn't even applied at all. As you can see in the image the coupon code is created and does exist.

![image](https://user-images.githubusercontent.com/10845460/114702690-af474880-9d24-11eb-9bb3-7ada8f50f29e.png)

### Steps To Reproduce:

1.  Laravel + Laravel/Cashier-paddle installation
2.  Create coupon code in Paddle
3.  Try to show the product prices with the coupons applied as said in the [documentation]((https://laravel.com/docs/7.x/cashier-paddle#prices):

**Comment by driesvints** [comment]
Works for me:

![Screenshot 2021-04-15 at 18 50 59](https://user-images.githubusercontent.com/594614/114907641-940b3480-9e1b-11eb-93e1-e047b249081f.jpg)

![Screenshot 2021-04-15 at 18 51 12](https://user-images.githubusercontent.com/594614/114907654-97062500-9e1b-11eb-916a-7166abc83514.jpg)

![Screenshot 2021-04-15 at 18 51 46](https://user-images.githubusercontent.com/594614/114907718-a5ecd780-9e1b-11eb-8907-ea29e4fc3bfc.jpg)

Please remember the note in the docs that you can't use this for subscription plans:

![Screenshot 2021-04-15 at 18 52 00](https://user-images.githubusercontent.com/594614/114907787-b9983e00-9e1b-11eb-88a8-3033f6d14af6.jpg)
