### ISSUE TITLE
Support CSP nonce for @paddleJS

### ISSUE THREAD

**Issue by greimers** [laravel/cashier-paddle#118]
When using CSP headers that blocks `unsafe-inline` scripts, you need to set a `nonce` for the script tags.
It would be great if the @paddleJS had a parameter to pass in that nonce similar to how LiveWire supports it with 
`@livewireScripts(['nonce' => csp_nonce()])`

I worked around this by manually pasting in the script tags from https://github.com/laravel/cashier-paddle/blob/1.x/resources/views/js.blade.php (hope that's all there is to it).

Context info: I use spatie/laravel-csp (https://github.com/spatie/laravel-csp)

**Comment by driesvints** [comment]
Can the same nonce be used for multiple scripts?

**Comment by greimers** [comment]
Yes, the nonce is generated for each page load and is send in the CSP header. That same nonce can then be assigned to all inline scripts. As I understand, the browser will then check the nonces in the page source against the nonce provided in the header.

**Comment by driesvints** [comment]
Can you send in a PR maybe? I think a single `$nonce` argument can be added.

**Comment by driesvints** [comment]
Closing this. Feel free to send in a PR.
