### ISSUE TITLE
TrimStrings middleware breaks signature verification

### ISSUE THREAD

**Issue by mpociot** [laravel/cashier-paddle#120]
- Cashier Paddle Version: 1.4.4
- Laravel Version: 8.43.0
- PHP Version: 8.0.5

### Description:

When a user enters any data with a leading/trailing whitespace, the signature verification is broken, because the `TrimStrings` middleware removed the whitespace, while the provided signature expects the whitespace.

### Steps To Reproduce:

Perform a Paddle request with a leading/trailing whitespace.

**Comment by driesvints** [comment]
Can you give a specific example of how to do this?

**Comment by mpociot** [comment]
It happened to me when having a whitespace in a passthrough parameter, but I think if you have whitespace in your name, it should happen too

**Comment by driesvints** [comment]
@mpociot I'll take a look tomorrow 👍

**Comment by driesvints** [comment]
This all works for me:

```php
Auth::user()->charge(12.55, 'Test Charge', ['passthrough' => ['test' => ' Test with space ']]);
```

![Screenshot 2021-05-28 at 10 51 54](https://user-images.githubusercontent.com/594614/119957860-c1aed600-bfa2-11eb-9c80-dea86b871678.jpg)

I tried also to set the name on the card with a leading and trailing space. Funny thing is that Paddle marked the name as invalid when I have a leading space but it doesn't when I have a trailing space. In any case, the trailing space also didn't cause the signature to be broken. I'll need more specific steps to reproduce this.

![Screenshot 2021-05-28 at 10 47 30](https://user-images.githubusercontent.com/594614/119958192-15212400-bfa3-11eb-9420-060a6923feba.jpg)

**Comment by mpociot** [comment]
Okay, then this only happens with a passthrough that contains a leading space:

```
Auth::user()->charge(12.55, 'Test Charge', ['passthrough' => '    Uh Oh']);
```

**Comment by driesvints** [comment]
That's not possible. You should get an exception for that. It's not possible to do a charge like that. The passthrough should always be an array. Are you overwriting this somehow?

https://github.com/laravel/cashier-paddle/blob/31c5c183f4f0f2c219785bc3bd84a2805d0e5d6c/src/Concerns/PerformsCharges.php#L67-L69
