### ISSUE TITLE
No permission to access resources only when checking for the next payment

### ISSUE THREAD

**Issue by Baspa** [laravel/cashier-paddle#128]
- Cashier Paddle Version: 1.2
- Laravel Version: 7.0
- PHP Version: 7.4

### Description:
I have an application where customers can buy subscriptions. This works perfectly fine, users can actually subscribe to subscription plans without any errors. They can even cancel their subscriptions etc. But when I want to check for the next payment I get the error: 

> You don't have permission to access this resource.

Because users can buy subscriptions and do other actions I assume that the credentials in my .env file are correct. I also double checked it multiple times and they are correct. The code where I check for the next payment date is this:

```
Client::query()
            ->each(function ($client) {
                $user = User::where('email', $client->email)->first();

                if ($client->subscription('default')) {
                    // Check if there is a next payment.
                    if ($client->subscription('default')->nextPayment()) {   <------ THIS IS THE RULE WHICH TRIGGERS THE ERROR
                        $nextPaymentDate = $client->subscription('default')->nextPayment()->date();

                        // Check if today is one day before payment.
                        if (Carbon::now()->addDays(1)->isSameDay($nextPaymentDate)) {
                            $user->setDiscountModifierAttribute();
                        }
                    }
                }
            });
```

### Steps To Reproduce:

Check for the next payment date on a client/user and the error will be triggered.

**Comment by ferrari308guy** [comment]
@Baspa Did you discover a solution? I'm running into the same issue...trying to access nextPayment() or lastPayment() results in a permissions error.
