### ISSUE TITLE
Possible bug with Safari 13.1.1

### ISSUE THREAD

**Issue by enkota** [laravel/cashier-paddle#13]
- Cashier Paddle Version: Latest Dev Build

### Description:
When trying to click the "Subscribe" pop-up after creating a payLink in Safari, the browser will hang and never load the pop-up. The same issue occurs when switching to inline checkout.

When attempting the same steps on Firefox or Chrome the pop-up will load correctly. I have cleared cookies/cache and extensions as well incase Safari was conflicting, but seeing the same issue. 

@techguydev was also experiencing issues getting the pop-up to appear via a Vue component too yesterday so I wonder if this could well be a Safari issue.

@driesvints are you able to recreate on Safari?

Thanks!

**Comment by enkota** [comment]
Update: Looks like an issue Paddles end. I have just tested on Table Plus who use Paddle and freezes on Safari - https://tableplus.com/pricing

I will report directly to Paddle and report back once fixed!

**Comment by driesvints** [comment]
Heya, I've always used the latest Safari to test and never experienced this. Thanks for looking into this. I'm closing this now but feel free to reply when Paddle gets back to you.
