### ISSUE TITLE
You don't have permission to access this resource

### ISSUE THREAD

**Issue by techguydev** [laravel/cashier-paddle#14]
- Cashier Paddle Version:1.0
Laravel Version: 7
- PHP Version: 7.4
- Database Driver & Version:

### Description:
After I have changed account and updated all the security parameter (id,public key etc) I am getting this error:

```Laravel/Paddle/Exceptions/PaddleException with message 'You don't have permission to access this resource```

has this happened to anyone?, what might trigger it?, I have doubled check all the details and they are alright.

It looks like to the .env details are being cached somewhere.

**Comment by driesvints** [comment]
Do all the resources in your database, your product ids in your code etc belong to the new account?

If it's an env issue: `php artisan config:clear`.

**Comment by techguydev** [comment]
Hi @driesvints  thanks a lot for the fast feedback.

it is solved now, it had confused the " Your API Key " with the "Auth Code" 

If this happens to some one too you have to select the information that is in this address:
```https://vendors.paddle.com/authentication````
Thanks

**Comment by HassanElshazlyEida** [comment]
I found that PADDLE_PUBLIC_KEY is incorrect which include only keys without -----BEGIN PUBLIC KEY----- and -----End PUBLIC KEY-----

**Comment by SRK90** [comment]
@HassanElshazlyEida  re: point 1, issue is not related to that. at least not in my case. in fact it has to be present.

faced same issue - use case:
while faking records, created subscriptions using 
```
$user->subscriptions()->create([
  'name' => 'default',
  'paddle_id' => random_int(1, 9999),
  'paddle_status' => 'active',
  'paddle_plan' => $planId,
  'quantity' => 1,
  'trial_ends_at' => null,
  'paused_from' => null,
  'ends_at' => null,                
]);
```

now, the billing page throws permission error, because it needs a entry in receipts table as well.
```
$user->receipts()->create([
  "billable_id" => 1,
  "billable_type" => "App\\Models\\User",
  "paddle_subscription_id" => 11111,
  "checkout_id" => "11111-1111111-11111",
  "order_id" => "1111-11111",
  "amount" => "100",
  "tax" => "10",
  "currency" => "USD",
  "quantity" => 1,
  "receipt_url" => "http://sandbox-my.paddle.com/receipt/1111-11111/11111-111111-11111",
]);

```

It worked after the above action.

**Comment by EeKay** [comment]
For me, this was because I still had PADDLE_SANDBOX = true in my production .env file. 
Removing it (or setting it to false) fixed this issue for me

**Comment by arqamsaleem1** [comment]
Is it required to verify the domain on the paddle as well? I'm encountering this error and working on my local machine where my domain is something like this http://127.0.0.1:8000/. Any idea how to resolve this issue?

**Comment by EeKay** [comment]
> Is it required to verify the domain on the paddle as well? I'm encountering this error and working on my local machine where my domain is something like this http://127.0.0.1:8000/. Any idea how to resolve this issue?

Your production account (vendors.paddle....) will only work when your domain was validated accordingly.

Working from localhost using the sandbox-venderos.paddle... environment did not require me to validate domains etc. 

If you're using the production environment from your localhost, I guess that won't because, as you indicated, validation hasn't been applied. I have no experience using localhost or public api services like NGROK with the production environment of Paddle.

**Comment by saadusufzai** [comment]
Use This link if you are testing it on local host or staging 

`https://sandbox-vendors.paddle.com/`

**Comment by saadusufzai** [comment]
Use This link if you are testing it on local host or staging

https://sandbox-vendors.paddle.com/

curl -X POST -d 'vendor_id=33315'
-d 'vendor_auth_code=73b583226fbe6bb42cd591e40fcb4234324232344'
-d 'subscription_id=580998'
-d 'amount=10.00'
-d 'charge_name=Plan Add-on Charge'
[https://sandbox-vendors.paddle.com/api/2.0/subscription/{subscription_id}/charge](https://sandbox-vendors.paddle.com/api/2.0/subscription/%7Bsubscription_id%7D/charge)
