### ISSUE TITLE
Query in Subscriber.php will throw a LazyLoadingViolationException if you've prevented lazy loading

### ISSUE THREAD

**Issue by joostvanhoof** [laravel/cashier-paddle#140]
- Cashier Paddle Version: 1.4.6
- Laravel Version: 8.62.0
- PHP Version: 8.0.9
- Database Driver & Version: MySQL 8

### Description:
There is a lazy loaded relationship that will throw a `LazyLoadingViolationException` if you've [prevented lazy loading](https://laravel.com/docs/8.x/eloquent-relationships#preventing-lazy-loading). Not sure if this is a bug, if not: please feel free to close this.

### Steps To Reproduce:
1. Subscribe to a plan
2. Cancel that plan
3. Subscribe to the same plan as done in step 1
4. Swap plans

The query in [Subscriber.php line 533](https://github.com/laravel/cashier-paddle/blob/807c00c10a049b07fbb096b56fee4e4f0f2bc456/src/Subscription.php#L533) will throw a `LazyLoadingViolationException` if you've prevented lazy loading.

**Comment by driesvints** [comment]
Hey @joostvanhoof, yes this is intended. It's not feasible to load the billable up front for every request. You can skip this model/relationship if you want by customizing `Model::handleLazyLoadingViolationUsing`.
