### ISSUE TITLE
PaddleException You don't have permission to access this resource

### ISSUE THREAD

**Issue by azankorejo** [laravel/cashier-paddle#142]
- Cashier Paddle Version: ^1.4
- Laravel Version: ^8.54
- PHP Version: 7.4.1
- Database Driver & Version:

### Description:

I just installed the cashier-paddle package for testing purposes and after setting up the environment keys for paddle sandbox account when I try a basic user subscription it brings up the exception given below

PaddleException You don't have permission to access this resource

btw I have checked the env keys and unlike the previous issue by techguydev

**Comment by Agusioma** [comment]
@azankorejo how did you go about this?
