### ISSUE TITLE
Unable to swap plans during trial

### ISSUE THREAD

**Issue by norbertjurga** [laravel/cashier-paddle#144]
Hello everyone! 

Although [documentation](https://laravel.com/docs/8.x/cashier-paddle#changing-plans) is quite clear that you should be able to do so and mantain the remaining trial: 

> **If the user is on a trial, the trial period will be maintained.** Additionally, if a "quantity" exists for the subscription, that quantity will also be maintained.

When using swap method during trial I'm getting **LogicException: Cannot swap plans while on trial**. 
https://github.com/laravel/cashier-paddle/blob/4137c72188cbcd7f2b35ebf1bcfff5e3be26f137/src/Subscription.php#L767

Thanks in advance!

**Comment by driesvints** [comment]
Resubmit this with a filled out issue template.
