### ISSUE TITLE
Unable to swap plans during trial

### ISSUE THREAD

**Issue by norbertjurga** [laravel/cashier-paddle#145]
- Cashier Paddle Version: 1.4.6
- Laravel Version: 8.73.1
- PHP Version: 7.4.7
- Database Driver & Version: MariaDB 10.4.13 

### Description:

Although [documentation](https://laravel.com/docs/8.x/cashier-paddle#changing-plans) is quite clear that you should be able to do so and mantain the remaining trial: 

> **If the user is on a trial, the trial period will be maintained.** Additionally, if a "quantity" exists for the subscription, that quantity will also be maintained.

When using swap method during trial I'm getting **LogicException: Cannot swap plans while on trial**. 
https://github.com/laravel/cashier-paddle/blob/4137c72188cbcd7f2b35ebf1bcfff5e3be26f137/src/Subscription.php#L767

### Steps To Reproduce:

Try using `$user->subscription('default')->swap(_paddle_id_);` for user on trial

**Comment by driesvints** [comment]
Thanks for noting us. This indeed is not possible and is a limitation of Paddle. See: https://developer.paddle.com/api-reference/subscription-api/users/updateuser#usage-notes

<img width="787" alt="Screenshot 2021-11-23 at 12 30 00" src="https://user-images.githubusercontent.com/594614/143017758-490ae577-fa0c-4276-9569-42b2dd7f3ef9.png">

I've sent in a PR to the docs to remove that section: https://github.com/laravel/docs/pull/7455
