### ISSUE TITLE
Incorrect next payment amount after swapping plans

### ISSUE THREAD

**Issue by norbertjurga** [laravel/cashier-paddle#146]
- Cashier Paddle Version: 1.4.6
- Laravel Version: 8.73.1
- PHP Version: 7.4.7
- Database Driver & Version: MariaDB 10.4.13 

### Description:
`$user->subscription('default')->nextPayment()->amount()` returns wrong amount after swapping plans always giving full price of the plan; this value differs from paddle's dashboard. 
#### Cashier's `Payment` instance ($61.5):
![Cashier's `Payment` instance](https://i.ibb.co/1LYqTtX/cashier.png)
#### Paddle's Dashboard ($43.05):
![Paddle's dashboard](https://i.postimg.cc/ZYNtVCmL/paddle2.png)

### Steps To Reproduce:
This problem exists when you swap from more expensive to cheaper plans:

Example:
When swapping from yearly ($650) to monthly ($65) subscription we can see on dashboard that next 10 payments are $0, when Cashier returns full plan's price.

**Comment by driesvints** [comment]
The screenshot of the dashboard is tiny and unreadable. Please upload a new one.

**Comment by norbertjurga** [comment]
@driesvints edited issue with better quality screenshot; sorry for that.

**Comment by norbertjurga** [comment]
@driesvints, I took a look at it, and it seems that in `swap` method the response has a good price
https://github.com/laravel/cashier-paddle/blob/d8671049f3e9981bd39c0a16f9a2d51670ba2694/src/Subscription.php#L537
`
"next_payment" => array:3 [▼
    "amount" => 0
    "currency" => "USD"
    "date" => "2021-12-26"
  ]
`


But  `paddleInfo's` getter has wrong amount in response
https://github.com/laravel/cashier-paddle/blob/d8671049f3e9981bd39c0a16f9a2d51670ba2694/src/Subscription.php#L751-L753

`  "next_payment" => array:3 [▼
    "amount" => 6.15
    "currency" => "USD"
    "date" => "2021-12-26"
  ]`

**Comment by driesvints** [comment]
I'm afraid there's nothing we can do here. We just consume what Paddle gives us. If the amount in the API is different from the amount in Paddle's dashboard then that looks like a bug to me on Paddle's end. It's best that you contact them about it. Feel free to respond back with any findings.

**Comment by norbertjurga** [comment]
FYI - info from paddle

> Yes, you are correct about the bug. Proration isn’t included in the 'next_payment' value when making the List Users API call, and if the customer has credit that rolls over multiple payments, this isn’t reflected in this value. Our Engineering Team is working on a solution at the moment.
> 
> I would like to mention that the team is currently working on some major infrastructural projects, so it is likely that they won't be able to deploy this fix as a priority. However, I am confident that we will be able to see this update in the future​.
