### ISSUE TITLE
How to check if the user is one trial or subscribed to any plan

### ISSUE THREAD

**Issue by techguydev** [laravel/cashier-paddle#15]
I have 3 different subscriptions : Basic,pro,unlimited.

I am planning to use policies to check if a user is subscribed to a determined plan or to some plan at all or if he/she is on trial, is there a function or a way to check  if a user is on trial of any plan or subscribed to any plan?

Thanks for this wonderful packages @driesvints , I am almost done with the implementation in my SaaS.

**Comment by techguydev** [comment]
I have found that with 
```
$user->onGenericTrial();

```

Works great to check if the user is on any trial.

Is there something similar to check if the user is on any active plan?

**Comment by techguydev** [comment]
```$user->subscriptions()->where('paddle_status','active')->count()  >= 1 ````
seems to work well to check if the user has any active subscription.

**Comment by driesvints** [comment]
Hey @techguydev, that's described here: https://laravel.com/docs/7.x/cashier-paddle#checking-subscription-status

![Screenshot 2020-06-22 at 13 16 33](https://user-images.githubusercontent.com/594614/85281621-9bc3ac00-b48a-11ea-9858-80e919c9e5fd.png)

Is that what you need?

**Comment by techguydev** [comment]
Hi @driesvints 
```
if ($user->subscribed('default')){

}
```
Works great if you have just one subscription type.

In my use case I have 3 subscriptions types:basic,pro,unlimited.

I am creating a workflow where I need to check if a given user has any subscriptions at all ( of any type) or if he/she  is on trial, or on trial with a given subscription.

I might just join them like this:

```
if ($user->subscribed('basic' || $user->subscribed('pro') || $user->subscribed('unlimited') ){
//
}
```
I just wanted to know if there is any function that consider any active subscription to a given user.

**Comment by driesvints** [comment]
Hey @techguydev, no there isn't such a feature atm it seems. If you indeed only need to check the active state you can do

```php
$user->subscriptions()->active()->count() >= 1
```

But that's not the same as `subscribed` which takes into account "valid" subscriptions:

```
    /**
     * Determine if the subscription is active, on trial, or within its grace period.
     *
     * @return bool
     */
    public function valid()
    {
        return $this->active() || $this->onTrial() || $this->onPausedGracePeriod() || $this->onGracePeriod();
    }
```

I'll mark this as a feature request.

**Comment by techguydev** [comment]
Thanks @driesvints

**Comment by frkcn** [comment]
> Hey @techguydev, no there isn't such a feature atm it seems. If you indeed only need to check the active state you can do
> 
> ```
> $user->subscriptions()->active()->count() >= 1
> ```

This PR fix this problem. https://github.com/laravel/cashier-paddle/pull/22

**Comment by techguydev** [comment]
@frkcn  looks insteresing

**Comment by Hussam3bd** [comment]
@techguydev 

I'm not sure but I think the right approach is to keep one subscription the "default"
and create 3 plans "Basic, pro, unlimited"

then you can check if the user subscribed and which plan the user subscribed to

```
if ($user->subscribedToPlan($monthly = 12345, 'default')) {
    //
}
```

I'm doing it this way in my SaaS,

**Comment by techguydev** [comment]
Thanks @Hussam3bd 

@driesvints What do you think about this approach?

**Comment by driesvints** [comment]
In general I agree yeah. I think in your use case you want different plans but one type of subscription.

I'm gonna leave the issue open for a bit because I can still see a use case of adding a method to see if a user has *any* active subscription at all.

**Comment by driesvints** [comment]
Closing this as it's now possible again to do `$user->subscriptions()->active()->count()` if you want.

**Comment by techguydev** [comment]
I am not sure I am understanding the difference between Subscription and Plan.

In my casa each plan has different access to my app, so the subscription if kind of different too.

how are you guys handling different access levels with different plans?
