### ISSUE TITLE
How to send passthrough and how to receive and store that passthrough after payment succeeded?

### ISSUE THREAD

**Issue by Anowar98** [laravel/cashier-paddle#151]
- Laravel Version: 7.0
- PHP Version: 8.0.10
- Database Driver & Version:

### Description:

I want to send the product id as an array with laravel cashier (paddle) passthrough and after payment succeeded, I want to store it in the database. But how to send passthrough and how to store that passthrough data after payment succeeded?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
