### ISSUE TITLE
isInitialPayment shows false even though it should be true

### ISSUE THREAD

**Issue by pmochine** [laravel/cashier-paddle#158]
- Cashier Paddle Version: v1.5.2
- Laravel Version: v9.5.1
- PHP Version: 8.0.14
- Database Driver & Version:

### Description:
I'm trying to work with the event `SubscriptionPaymentSucceeded` but while using the public method `isInitialPayment()`, I noticed that it's not working correctly.

To fix the "bug" it should be 

  ```
public function isInitialPayment()
{
    (int) return $this->payload['initial_payment'] === 1;
}
```

**Comment by driesvints** [comment]
Hmm that's odd since it should definitely be an integer: https://developer.paddle.com/webhook-reference/ZG9jOjI1MzUzOTk3-subscription-payment-succeeded

<img width="669" alt="Screenshot 2022-03-28 at 14 05 43" src="https://user-images.githubusercontent.com/594614/160394232-5b04da13-ffce-41bc-b1e9-c608a6973b63.png">

**Comment by driesvints** [comment]
I sent in a PR for this: https://github.com/laravel/cashier-paddle/pull/159

**Comment by pmochine** [comment]
@driesvints thanks for your fast response and PR. I made a small logger test for you

```
logger($event->payload['initial_payment'] === 1 ? 'true' : 'false');
logger((int) $event->payload['initial_payment'] === 1 ? 'true' : 'false');
```

And if I look into my logs, I see: 
```
[2022-03-28 12:10:53] production.DEBUG: false  
[2022-03-28 12:10:53] production.DEBUG: true
```

**Comment by driesvints** [comment]
@pmochine so it works for you? Btw, you're not placing the array call and type cast between `( )`. 

Can you dump the contents of `$event->payload`?

**Comment by pmochine** [comment]
@driesvints No, it doesn't work. I just wanted to show you that I need to type cast `$event->payload['initial_payment']` to integer so only then does it show "true". 

And here is the payload:

```
"payload":{
      "alert_id":"...",
      "alert_name":"subscription_payment_succeeded",
      "balance_currency":"EUR",
      "balance_earnings":"292.46",
      "balance_fee":"17",
      "balance_gross":"331.12",
      "balance_tax":"21.66",
      "checkout_id":"...",
      "country":"TH",
      "coupon":null,
      "currency":"THB",
      "customer_name":"...",
      "earnings":"11121.89",
      "email":"...",
      "event_time":"2022-03-28 10:47:56",
      "fee":"646.49",
      "initial_payment":"1",
      "instalments":"1",
      "marketing_consent":"0",
      "next_bill_date":"2023-03-28",
      "next_payment_amount":"12592.17",
      "order_id":"...",
      "passthrough":"....",
      "payment_method":"card",
      "payment_tax":"823.79",
      "plan_name":"Yearly",
      "quantity":"1",
      "receipt_url":"...",
      "sale_gross":"12592.17",
      "status":"active",
      "subscription_id":"...",
      "subscription_payment_id":"...",
      "subscription_plan_id":"...",
      "unit_price":"12592.17",
      "user_id":"...",
      "p_signature":"..."
   }
```

And as you notice, every property from `payload` comes as a string. Not sure if this should be like that. If I look at the dump contents of `receipt`, I see integer values.

Besides, I'm not sure what you mean with `you're not placing the array call and type cast between ( )`

**Comment by driesvints** [comment]
> I just wanted to show you that I need to type cast $event->payload['initial_payment'] to integer so only then does it show "true".

That's exactly what I'm doing in my PR. The snippet you posted:

`logger((int) $event->payload['initial_payment'] === 1 ? 'true' : 'false');`

Is wrong. You need to do `((int) $event->payload['initial_payment']) === 1`
