### ISSUE TITLE
Upcoming Changes to ID format for Invoicing

### ISSUE THREAD

**Issue by Rydgel** [laravel/cashier-paddle#169]
I received yesterday an email from Paddle saying some API fields are going to be moved from integer to string.
I was wondering if this library will support this change.

Here is the email:

> Hi there,

> The reason we are contacting you today is to inform you that on Monday, 24/10/2022 we will introduce a new format for the Invoice, Product and Customer IDs used by our Invoicing Tool. Currently, we are using UUID as ID format, however, in preparation for ID format alignment across our new APIs, we are introducing the Paddle ID.

>What is the Paddle ID?
>A Paddle ID is a string made up of a prefix to identify the entity the ID represents, combined with a ULID. It should be treated as an opaque string.

>Example: inv_01gbwf7pezzb56efp2far9a678

>What fields are changing?
>The fields that are changing are the Invoice ID, Product ID and Customer ID. These fields are exposed via the Invoicing CSV and webhooks.

>For backwards compatibility, we will leave the UUID format in place for the Invoice ID in the CSV and webhooks.

>How will you be affected?
>If you are storing Product ID and/ or Customer ID, please make sure you store these as a string as opposed to UUID to ensure your setup will still work as expected when we do the change on Monday next week.

>While we’re leaving the UUID in place for the Invoice ID, we also recommend storing this as a string as well.

>If you’d like to test your setup, you can do so in Sandbox where this change has already been deployed.

>If you have any questions, please feel free to respond to this email and we’ll be happy to help.

>Kind regards,

>Paddle Customer Support

**Comment by driesvints** [comment]
Hi there. Judging from these changes, we have no reason to believe it'll break Cashier Paddle.
