### ISSUE TITLE
The swap method don't support rename the subscription on the subscriptions table.

### ISSUE THREAD

**Issue by ricardov03** [laravel/cashier-paddle#181]
- Cashier Paddle Version: 1.8.1
- Laravel Version: 9.50.2
- PHP Version: 8.1.14
- Database Driver & Version: MySQL 8.0.32 

### Description:
I'm using Cashier Paddle with the default Billable different from the User model. I'm using the swap method from the Subscription model from the Cashier Paddle package. After changing the subscription, the subscription name maintains the same name on the `subscriptions` table on the database. I was trying to figure out if there is any method to set the name on the process, but I didn't find any. Can anybody help me with this? I appreciate any help you can give me.

### Steps To Reproduce:

```php
...
$subscription = auth()?->user()?->tenant?->subscriptions->sortByDesc('id')?->first();
$subscription->swap($request->newPlan);
```

**Comment by driesvints** [comment]
The subscription name is never meant to change. It’s your identifier for the type of subscription, not a human readable name.

**Comment by ricardov03** [comment]
First, Dries, thanks for taking the time to answer my question. Your answer sent me to another question because it looks like I don't get the real purpose of the subscription name as you defined on the package. For example, if I have two subscriptions, let's say `base` and `premium`, If a user subscribes to the base one for the first time, I will use `base` as the name of the subscription. But, If the user swap from the `base` to the `premium`, it's not `premium` the name of the new subscription?

Please help me to understand If I'm seeing the name right or not. Thank you so much for your attention and help.

**Comment by ricardov03** [comment]
Thank you so much for taking the time to explain how it works. So, in this case, the only relation we have with the Plan is the `paddle_id`?

**Comment by driesvints** [comment]
Correct
