### ISSUE TITLE
JPY has two extra zeroes.

### ISSUE THREAD

**Issue by patrickomeara** [laravel/cashier-paddle#183]
### Cashier Paddle Version

1.8.1

### Laravel Version

9.52.6

### PHP Version

8.2.3

### Description

As mentioned here https://github.com/moneyphp/money/issues/684 by @driesvints there is an issue formatting JPY. The mentioned solution looks to be implemented in `Cashier::formatAmount()` However I am still getting an extra 2 zeroes for JPY, all other currencies work fine.

@driesvints Is this a known issue that we have to handle in our application code?

<img width="502" alt="image" src="https://user-images.githubusercontent.com/571773/234519712-16828172-2874-48a7-99bb-ef31bd15d62d.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/571773/234519770-caf1c00f-5b84-4e64-a7df-5e93c6aa40aa.png">

### Steps To Reproduce

Format a paddle price using `JP` country_code

**Comment by driesvints** [comment]
How are you displaying the price?

**Comment by patrickomeara** [comment]
I've tried `->price()->gross()` as in the docs and tried using `Cashier::formatAmount()` directly.

```php

Route::get('cashier', function() {
    return Cashier::productPrices(
        collect(Arr::dot(config('billing.plans')))
            ->values()
            ->toArray(), ['customer_country' => 'JP']
    )->map(fn (ProductPrice $price) => $price->price()->gross());
});
```

**Comment by driesvints** [comment]
Hah, actually, it's not showing any decimal at all. You're being displayed 120000 Japanese Yen. This is because the modifier for other currencies shouldn't apply here. I've attempted to fix this here: https://github.com/laravel/cashier-paddle/pull/184

Can you try out that PR and let me know if things look better?

**Comment by patrickomeara** [comment]
Yep, sorry if that wasn't clear. Your solution in #184 will definitely work, as it's the same workaround I've just put live.

```php

        $multiplier = $productPrice->currency === 'JPY' ? 1 : 100;

        return Cashier::formatAmount(
            (int) $productPrice->price()->rawGross() * $multiplier,
            $productPrice->price()->currency(),
            null,
            ['min_fraction_digits' => 0]
        );
```
