### ISSUE TITLE
Paddle Billing api support

### ISSUE THREAD

**Issue by suhailpatel49** [laravel/cashier-paddle#195]
Accounts created from 8th August 2023 onwards have the "Paddle Billing" enabled. "Paddle Classic" is no longer available.
Looking at the source code; cashier-paddle is using the "Paddle Classic" apis. Do we have it in the roadmap to provide api support for "Paddle Billing"?

The classic apis are not providing proper response for "Paddle Billing".

**Comment by driesvints** [comment]
Please see https://github.com/laravel/cashier-paddle/issues/192
