### ISSUE TITLE
Method "isValidSignature" actually is "isInvalidSignature"

### ISSUE THREAD

**Issue by SebastianSchoeps** [laravel/cashier-paddle#20]
Hi,

functionality is right, but `VerifyWebhookSignature@isValidSignature` actually checks if the signature is invalid. I would propose to leave the method name, but return `return openssl_verify(...) === 1` instead of `return openssl_verify(...) !== 1` and change `if ($this->isValidSignature($fields, $signature)) {` to `if (!$this->isValidSignature($fields, $signature)) {`.

https://github.com/laravel/cashier-paddle/blob/a99ab8f980095b47eb69cab249e17b1a2895d9b5/src/Http/Middleware/VerifyWebhookSignature.php#L65

PR?

Sebastian

**Comment by driesvints** [comment]
Good spot! I've updated the method name.
