### ISSUE TITLE
Unable to find requested product

### ISSUE THREAD

**Issue by makssein** [laravel/cashier-paddle#200]
### Cashier Paddle Version

1.9.1

### Laravel Version

9.45.1

### PHP Version

8.0

### Database Driver & Version

MySQL

### Description

I'm using sandbox to test my application. I created one product that has one price. I have also added all the necessary information to connect my account.
 
When I try to buy a subscription I get the response "Unable to find requested product"
As an ID, I tried to use the product ID pro_* and the price ID pri_*. In both cases the answer is the same.
```
$user->newSubscription('default', "pro_asdasd......")
        ->create();
```

### Steps To Reproduce

-

**Comment by driesvints** [comment]
This sounds more a question for paddle itself sorry.

**Comment by makssein** [comment]
@driesvints 
It seems to me that paddle has created a new version of its api.
1) When creating a product, I am at the url /products-v2, but if I go to /products, I can create a product with a numeric ID.
2) The paddle documentation states everywhere that ID is a string, not a number
3) The documentation uses api.paddle.com and cashier-paddle uses vendors.paddle.com/api/2.0

**Comment by driesvints** [comment]
ah yes. Please see https://github.com/laravel/cashier-paddle/issues/192 & https://github.com/laravel/cashier-paddle/pull/198
