### ISSUE TITLE
Paddle Billing

### ISSUE THREAD

**Issue by makssein** [laravel/cashier-paddle#201]
### Cashier Paddle Version

1.9.2

### Laravel Version

9.52.16

### PHP Version

8.1

### Database Driver & Version

MySQL

### Description

Hello! 

How is work going on the new version of Paddle Billing? Will it be ready soon (approximate time frame, perhaps)? 

Your library is very convenient to work with, however I cannot use the current version, unfortunately 😢.

### Steps To Reproduce

-

**Comment by driesvints** [comment]
https://github.com/laravel/cashier-paddle/issues/192
