### ISSUE TITLE
The switch between the sandbox and production requires its own public key

### ISSUE THREAD

**Issue by Benoit1980** [laravel/cashier-paddle#204]
Hello,

I've noticed that several users are encountering the "Paddle, you do not have the permission to access this resource" error. After investigating, I found that the root cause is related to the usage of of the same Paddle credentials in both production and sandbox environments.

In your current configuration in the .env file, you have:

```
PADDLE_VENDOR_ID=
PADDLE_VENDOR_AUTH_CODE=
PADDLE_PUBLIC_KEY=
PADDLE_SANDBOX=false
```
However, when switching between production and sandbox environments, Paddle requires entirely different credentials. 
To address this issue, please consider adding extra ENV variable please:

# Production Credentials
PADDLE_VENDOR_ID=
PADDLE_VENDOR_AUTH_CODE=
PADDLE_PUBLIC_KEY=

```
# Sandbox Credentials
SANDBOX_PADDLE_VENDOR_ID=
SANDBOX_PADDLE_VENDOR_AUTH_CODE=
SANDBOX_PADDLE_PUBLIC_KEY=
```

Thank you.

**Comment by driesvints** [comment]
Yes, that's indeed correct. You'll need to update your credentials for a sandbox env. Right now we have no plans to add extra credentials separately for sandbox. You can have duplicate env variables and comment one pair out in your env file if you wish.
