### ISSUE TITLE
Fix incrementQuantity() & decrementQuantity() Throwing Error

### ISSUE THREAD

**Issue by haszzam** [laravel/cashier-paddle#224]
### Cashier Paddle Version

2.x

### Laravel Version

10.10

### PHP Version

8.1

### Issue (1)

The `incrementQuantity()` method was failing and throwing the error below.

![image](https://github.com/laravel/cashier-paddle/assets/42672551/2c3d7026-7fec-499b-ac7d-c45a4a6f98f9)

In the `updateQuantity()` running `pluck(['quantity', 'price_id'])` on the result from `get(['quantity', 'price_id'])` was returning null in the following line
`$items = $this->items()->get(['quantity', 'price_id'])->pluck(['quantity', 'price_id'])->toArray();`

I'm also not sure you could pass and array to `pluck`, I think this was added by mistake.

### Solution (1)

Removed `pluck(['quantity', 'price_id'])`

### Steps To Reproduce (1)

Try running `$user->subscription()->incrementQuantity(1, 'price_id');`.

### Issue (2)
The `decrementQuantity()` method was failing and throwing the error below.

![image](https://github.com/laravel/cashier-paddle/assets/42672551/48ea9880-bc14-4018-a781-5130c14b5b5c)

The problem is that the `decrementQuantity()` is not passing the `$item` or the `$price_id` to the `updateQuantity()` method as you can see below
![image](https://github.com/laravel/cashier-paddle/assets/42672551/9241bfaa-90fa-4b0f-af2b-38500751f8cb)

### Solution (2)
Pass the `$item` instance to the `updateQuantity()` method.
`return $this->updateQuantity(max(1, $item->quantity - $count));`

### Steps To Reproduce (2)

Try running `$user->subscription()->decrementQuantity(1, 'price_id');`.

**Comment by haszzam** [comment]
Hi @driesvints,

I know i'm bothering you a lot lately, But I tried to send a pull request with the fix for this issue but it failed the tests with the following message `"Paddle API key not set."` I don't know where should I set the key and if I even should set a Paddle API key publicly.

If you can check it out and let me know what I have done wrong to fail the tests I would really appretiate it so that I can send a pull request directly if I found any other issues.

https://github.com/laravel/cashier-paddle/pull/223#issue-2044669672

Thanks!

**Comment by driesvints** [comment]
@haszzam heya! Sorry for the late reply here. Don't worry about it. I appreciate you notifying us! I've sent in a PR here: https://github.com/laravel/cashier-paddle/pull/226

**Comment by haszzam** [comment]
Hi @driesvints, Thank you!

BTW I checked the PR and it's only including the fix for the issue (1).
It does not fix the second issue with the `decrementQuantity()`.

**Comment by driesvints** [comment]
Oh you're correct. Added that as well 👍

**Comment by haszzam** [comment]
Thanks @driesvints I really appreciate your help!
