### ISSUE TITLE
Notice in the docs about "default checkout URL"

### ISSUE THREAD

**Issue by GoodM4ven** [laravel/cashier-paddle#225]
Greetings,

If the the **default payment link** isn't set in Paddle's [checkout settings](https://sandbox-vendors.paddle.com/checkout-settings), then the moment the subscription button (`$checkout`'s) is clicked, and where the overlay is used, the payment overlay will show a vague "please contact support" sort of message, and JS will throw this `transaction_default_checkout_url_not_set` error; which can only be seen upon dev-tools inspection.

![image](https://github.com/laravel/cashier-paddle/assets/121377476/bd205c65-cf59-4824-afbc-f3f931302994)

I suggest adding a bold warning in the docs somewhere about this.

Thank you.

**Comment by driesvints** [comment]
Thanks! I added this here: https://github.com/laravel/docs/pull/9211
