### ISSUE TITLE
Enable opt-in Subscription model publishing

### ISSUE THREAD

**Issue by alihusic** [laravel/cashier-paddle#23]
Every system where one user can have multiple subscriptions (for example owns multiple organizations with different subscription plans) would need to have some additional internal subscription information (maybe a foreign key).

I think it would be beneficial to allow publishing the Subscription model so that some methods and fillable fields may be overriden.

If this is already possible, please explain it since the docs don't hint at Subscription customization other than the migration publishing.

Also yes, this could be solved with creating another table which has a 1:1 foreign key to the subscription and contains additional subscription info. However, this can be too much overhead for an additional 1-3 columns.

**Comment by driesvints** [comment]
In general I recommend keeping your custom database scheme separate than that from Cashier. Especially in the next beta where we'll introduce a model that's completely separate (even the customer database fields). So I think the 1:1 approach is the way to go here.
