### ISSUE TITLE
Bill for non-catalog items

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier-paddle#230]
Add support for https://developer.paddle.com/changelog/2023/add-custom-items-transaction

**Comment by driesvints** [comment]
Btw, we'd love to get a PR for this.

**Comment by HelgeSverre** [comment]
Hey Dries,

We're likely to need this feature at [Crescat](https://crescat.io/products/) soon-ish, so I can take a crack at this, since we're planning on implementing this feature in our application anyways, (and when Paddle releases it; add support for recurring non-catalog items on subscriptions).

Do you have any thoughts/preference around the API for this feature?

Throw me some notes if you have any and I'll take a look at it.

**Comment by driesvints** [comment]
Hey @HelgeSverre. Thanks for wanting to help out here! I think it would be similar to https://github.com/laravel/cashier-paddle/blob/1.x/src/Concerns/PerformsCharges.php#L21

I haven't really dug deep into what's needed for this so if you could whip up something working we can go from there. Thanks!

**Comment by movicat** [comment]
$items = [
            'items' => [
                [
                    'quantity' => 1,
                    'price' => [
                        'description' => 'asdasd',
                        'name' => 'ddddd',
                        'billing_cycle' => null,
                        'trial_period' => null,
                        'tax_mode' => 'account_setting',
                        'unit_price' => [
                            'amount' => '1000',
                            'currency_code' => 'USD',
                        ],
                        'unit_price_overrides' => [],
                        'quantity' => [
                            'minimum' => 1,
                            'maximum' => 100,
                        ],
                        'custom_data' => null,
                        'product' => [
                            'name' => 'Promo',
                            'description' => null,
                            'tax_category' => 'standard',
                            'image_url' => null,
                            'custom_data' => null
                        ]
                    ]
                ]
            ]
        ];

        $url = 'transactions';
        $response = Cashier::api('post', $url, $items);

        // Check if the user is not logged in
        if(!Auth::check()) {
            // If not logged in show a message.
            Notification::make()
                ->title(__('Please login to subscribe.'))
                ->danger()
                ->send();
            return;
        }
        
        $checkout = Auth::user()->checkout('pri_01ht33svsvkr4ff7qfkdc7m27m')
            ->customData(['order_id' => 12]);
        $options = $checkout->options();

        $options['settings']['displayMode'] = 'overlay';
        $options['transactionId'] = $response['data']['id'];
        unset($options['items']);
        
        $options = json_encode($options);
        $this->js("Paddle.Checkout.open({$options});");

**Comment by movicat** [comment]
temporary solution

**Comment by HelgeSverre** [comment]
Sorry for the disappearance, priorities got shifted around, I wont get around to look at this for a little while longer, so if anyone else wants to jump at this, feel free.

**Comment by AcTiv3MineD** [comment]
Hi @driesvints, I have created pull request for this issue.

It basically allows to create transactions on paddle and pass the transaction id as a html attribute to the button.

------

I'm open to any suggestions, let me know if the current implementation is a good fit or what needs to be changed.

**Comment by driesvints** [comment]
This will be in Tuesdays release
