### ISSUE TITLE
Add support for authentication via client-side tokens

### ISSUE THREAD

**Issue by Persaeus** [laravel/cashier-paddle#244]
Some methods in Paddle.js are only available when using client-side tokens for authentication. For example, [Paddle.PricePreview()](https://developer.paddle.com/paddlejs/methods/paddle-pricepreview#paddle.pricepreview()):

> Requires [a client-side token for authentication](https://developer.paddle.com/api-reference/about/authentication). If you're passing the older seller parameter to Paddle.Setup(), replace this with token to use Paddle.PricePreview().

**Comment by driesvints** [comment]
Falls a little outside the scope of this library sorry.
