### ISSUE TITLE
Applying a discount on checkout

### ISSUE THREAD

**Issue by mshamaseen** [laravel/cashier-paddle#253]
would be great if the ability to apply a discount is added to checkout.
something like:

```
$checkout = $user->subscribe($id)->applyDiscount($discountId)
                ->returnTo(route('thanks'));
```

**Comment by driesvints** [comment]
This is something that's handled by Paddle's widget. Afaik there's no way to add this up front?

**Comment by DanjBethel** [comment]
@driesvints From paddle documentation page:

```
Use discount codes to let customers apply discounts themselves at checkout, or pass a discount to a checkout to apply it automatically.
```

How can this be done with the current implementation?
