### ISSUE TITLE
Paddle API error 'empty patch update' occurred

### ISSUE THREAD

**Issue by KareemHussen** [laravel/cashier-paddle#271]
### Cashier Paddle Version

2.5

### Laravel Version

10.0

### PHP Version

8.1

### Database Driver & Version

MYSQL

### Description

When i try to swap the  current subscription it gives me this error : Paddle API error 'empty patch update' occurred
note that it's the only invalid endpoint the rest are ok

### Steps To Reproduce

here's  my  code
```
public function update(UpdateSubscriptionRequest $request)
    {
        $data  = $request->validated();
        $user  = $request->user;

        $user->subscription()->swap($data['price_id']);

        return $this->respondOk(SubscribtionResource::make($user->subscription()->asPaddleSubscription()) , "Subscribtion swapped successfully");
    }
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
