### ISSUE TITLE
Get next_bill_date for a subscription

### ISSUE THREAD

**Issue by alzaabi98** [laravel/cashier-paddle#28]
Normally for any subscription user should know their next payment date . It will be good idea if there is a way to update subscription table to next_bill_date. There is data coming from paddle "next_bill_date" when order is completed but not sure if there a webhook to update this information or if there is a way cachier-paddle can pull information from time to time and update all subscription table with new data such as status, next bill date etc.

**Comment by driesvints** [comment]
Hey @alzaabi98. You have `lastPayment` and `nextPayment` on the `Subscription` model which will return an instance of `Laravel\Paddle\Payment` (or `null` if there isn't a next payment anymore). I'll try to document this.

**Comment by alzaabi98** [comment]
> Subscription

Thanks for your answer, it will be great to show how can I access this model. I tried $user->subscription()->lastPayment but it does not work.

**Comment by driesvints** [comment]
Is your subscription name `default`? Because depending if your subscription has a different name you'll have to pass that explicitly:

```php
$user->subscription('other-name')->lastPayment();
```

**Comment by alzaabi98** [comment]
@driesvints  yes it worked for me now .. thanks again !
