### ISSUE TITLE
Webhook: Invalid webhook signature while everything seems right setup

### ISSUE THREAD

**Issue by PaulBorie** [laravel/cashier-paddle#283]
### Cashier Paddle Version

2.5.2

### Laravel Version

11.25.0

### PHP Version

8.3.7

### Description

I can't make Paddle webhooks working while everything seems setup right. I constantly get 403 error  response from my app
```json
"message": "Invalid webhook signature.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException",
    "file": "/home/user/myapp/vendor/laravel/cashier-paddle/src/Http/Middleware/VerifyWebhookSignature.php",
    "line": 33,
```
I exposed my local machine using ngrok with a static domain. 
I added a webhook endpoint on my Paddle Sandbox pointing to my https://ngrok_static_domain/paddle/webhook
I retrieved the PADDLE_WEBHOOK_SECRET variable from this newly created webhook starting with "pdl_" and set it to my `.env` file. I tried to write it with and without quote.
I cleared cached config many times and dump config('cashier.webhook_secret') displaying the right secret.

The signature header in the Paddle webhook request to my server is presen: 
Paddle-Signature: ts=1728935049;h1=1f71aae5ce2ed647bad4b3d4b36**************************7c34ae7f

### Steps To Reproduce

Setup a new Laravel project, install paddle cashier and add a create a checkout view `checkout.blade.php`. Setup all the necessary env keys from your paddle account and pay using the checkout to trigger the webhook. 
```php
<?php
$options = $checkout->options();
$options['settings']['frameTarget'] = 'paddle-checkout';
$options['settings']['frameInitialHeight'] = 366;
$options['settings']['theme'] = 'light';
$options['settings']['variant'] = 'one-page';
?>
 @push('paddle-scripts')
        @paddleJS
 @endpush
 <div class="p-1 lg:p-8 ">
           <div
                 class="paddle-checkout"
                 x-data="{}"
                 x-init="Paddle.Checkout.open(@js($options));">
           </div>
</div>
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by PaulBorie** [comment]
Hi!
Sorry for opening an issue unnecessarily. I thought Paddle might have changed the way they sign their webhooks. Actually  my Ubuntu dev machine what not synced with NTP clock servers anymore causing the `isInvalidSignature` function in the`VerifyWebhookSignature` middleware to fail. Especially this line made if fail. 
```php
if ($this->maximumVariance > 0 && time() > $timestamp + $this->maximumVariance) {
            return true;
}
``` 
Just had to resync my Ubuntu laptop with NTP servers ! 
Thanks
