### ISSUE TITLE
Discounts

### ISSUE THREAD

**Issue by makssein** [laravel/cashier-paddle#286]
### Cashier Paddle Version

2.4.2

### Laravel Version

10.37.3

### PHP Version

8.1

### Description

How do I apply discounts?
The only mention of discounts in the documentation is when previewing prices. How do I specify the discount_id parameter when creating a new subscription or simply when purchasing a product?

For example, I do the following, how do I apply my discount to my subscription?

```
$prices = $user->previewPrices([
                $monthly_price,
                $annually_price
            ],
                [
                    'customer_ip_address' => $user->ip,
                    'discount_id' => $black_friday_discount
                ]);

            $checkout = $user->subscribe(
                $annually_price,
                config('subscriptions.name')
            )
                ->returnTo(route('checkout.status'));
```

### Steps To Reproduce

-

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
