### ISSUE TITLE
The customer search in `createAsCustomer` is too permissive

### ISSUE THREAD

**Issue by Rydgel** [laravel/cashier-paddle#289]
### Cashier Paddle Version

2.5.3

### Laravel Version

11

### PHP Version

8.3

### Description

Inside the method `createAsCustomer` we are looking for existing Customer inside Paddle.
This piece of code here:

```php
// Attempt to find the customer by email address first...
$response = Cashier::api('GET', 'customers', [
    'status' => 'active,archived',
    'search' => $options['email'],
])['data'][0] ?? null;
```

The problem is that the search field does a fuzzy search on various field:
> Return entities that match a search query. Searches id, name, and email fields. Use the email query parameter for precise matching of email addresses.

In our production code we had errors where `dude1@domain.fr` search was returning `girl1@domain.fr`

In my opinion we need to use the `email` field instead:
>Return entities that exactly match the specified email address. Use a comma-separated list to specify multiple email addresses. Recommended for precise matching of email addresses.

I'm proposing a fix in pull request: https://github.com/laravel/cashier-paddle/pull/288

### Steps To Reproduce

Paddle Documentation is enough imo

**Comment by arvidkahl** [comment]
Until this pull request makes it into the library, this can be solved by taking the `createAsCustomer` function from ManagesCustomer.php in `laravel-cashier-paddle` and monkeypatching your billable model with it, switching `search` for `email` like in @Rydgel's commit. Not very elegant, but will prevent your customers from being unable to sign up.

**Comment by taylorotwell** [comment]
Merged PR.

**Comment by Rydgel** [comment]
@arvidkahl yep, this is what we did 😃 
@taylorotwell thanks!
