### ISSUE TITLE
How to get plan name and amount

### ISSUE THREAD

**Issue by alzaabi98** [laravel/cashier-paddle#32]
Is there any way to bring subscription plan name and amount along with subscription model ? now I can see only plan id. other way is to maintain another table in backend to hold paddle plan id and other plan details manually.

**Comment by driesvints** [comment]
Hey @alzaabi98. That's documented here: https://laravel.com/docs/7.x/cashier-paddle#prices

More info about the endpoint that's being used can be found here: https://developer.paddle.com/api-reference/checkout-api/prices/getprices

There's also https://developer.paddle.com/api-reference/subscription-api/plans/listplans if you want to consume the API directly.

**Comment by driesvints** [comment]
In general I'd recommend to use the prices functionality because you can limit the plans to only the ones you want. The listplans endpoint just returns all plans on the account.

**Comment by alzaabi98** [comment]
@driesvints 
i want my user to be able to visit subscription page in my website and then he can view what plans he subscribed to .. monthly ,yearly.

also to provide option to swap plans,

i dont see how prices can get me this data , currently , i am sending him this info 

```
    $data = [
                'subscription' => $user->subscription('default'),
                'nextPayment' => $user->subscription('default')->nextPayment(),
                'lastPayment' => $user->subscription('default')->lastPayment(),

            ];

```
I want also to show him name of the plan .

**Comment by driesvints** [comment]
Hey @alzaabi98. I'm very happy to help you out but this is again something that is directly said in the docs: https://laravel.com/docs/7.x/cashier-paddle#prices

![Screenshot 2020-07-07 at 13 07 39](https://user-images.githubusercontent.com/594614/86771629-da449380-c052-11ea-954f-e2e82394725a.png)

Can you please read the docs carefully before opening issues? Thanks.

**Comment by driesvints** [comment]
Btw, the next beta will include support for checking the billing interval, etc.: https://github.com/laravel/cashier-paddle/pull/24

**Comment by alzaabi98** [comment]
@driesvints  Thanks for you quick answers. it is appreciated. i have read the docs until i feel i need to ask. I dont want to open issue just because I want to open issue. if there is another way to ask then it will be great to avoid opening new issues.  What I need to have full information for subscription to show it user.

**Comment by driesvints** [comment]
@alzaabi98 there's the #cashier channel on Discord which might be a bit more appropriate. Issue trackers on the repos are mainly for reporting bugs but during the beta period I don't mind that.
