### ISSUE TITLE
How to generate invoice for users

### ISSUE THREAD

**Issue by alzaabi98** [laravel/cashier-paddle#33]
Does the package provide any means to generate invoices or this has to be manual process ?

**Comment by GrahamCampbell** [comment]
Note that if you are using Paddle, you are legally not allowed to generate invoices yourself. You have to have Paddle issue them, because they are the merchant of record. You are not the seller, they are.

**Comment by driesvints** [comment]
@GrahamCampbell is correct. Plus Paddle doesn't even gives us all the info through the API that we'd need (like address, individual line items, etc).

**Comment by alzaabi98** [comment]
@GrahamCampbell @driesvints 
so how can customer get invoices then ? if someone registered  in my site and then subscribe to plan let us say monthly . how he can generate invoices. ? at this time my site charged him using cahier-paddle but he cant access paddle directly as he does have account there  ? still not getting the full picture.

i know most sites offered a button to download invoice for in subscription page like in laracasts for example.

**Comment by driesvints** [comment]
@alzaabi98 I think you missed this section in the documentation: https://laravel.com/docs/7.x/cashier-paddle#transactions

![Screenshot 2020-07-07 at 12 49 20](https://user-images.githubusercontent.com/594614/86769981-4a9de580-c050-11ea-9e95-7a30167716de.png)

**Comment by alzaabi98** [comment]
> @alzaabi98 I think you missed this section in the documentation: https://laravel.com/docs/7.x/cashier-paddle#transactions
> 
> ![Screenshot 2020-07-07 at 12 49 20](https://user-images.githubusercontent.com/594614/86769981-4a9de580-c050-11ea-9e95-7a30167716de.png)

@driesvints  yes i did  ,, as i was searching "generate invoices" ,  the doc is not clear as cachier-stripe which has for example sections called 
<img width="416" alt="Screen Shot 2020-07-07 at 4 31 17 PM" src="https://user-images.githubusercontent.com/7835187/86781970-9d3aca00-c06f-11ea-89e8-4a4e7dbb6a01.png">

**Comment by driesvints** [comment]
Cashier Stripe and Cashier Paddle are two totally different libraries just like Stripe and Paddle are two totally different services. They don't offer the exact same functionality.

**Comment by zackAJ** [comment]
here you go
```
Route::get('invoice',function(){
    $trans =  request()->user()->transactions()->first();
    return "<a href='{$trans->invoicePdf()}' target='_blank'>invoice</a>";
});
```
