### ISSUE TITLE
Cancellation subscription - Call to a member function date() on null

### ISSUE THREAD

**Issue by Hussam3bd** [laravel/cashier-paddle#37]
- Cashier Paddle Version: dev-master
- Laravel Version: 7.19
- PHP Version: 7.4
- Database Driver & Version: mysql

### Description:

This error happened when I cancel a subscription

```
$subscription->cancel();
```

https://share.getcloudapp.com/eDu1Z0yK

This error happened only if the subsection status still active, and it will be active until Paddle's webhook sent the response to the server and being handled.

**Comment by GrahamCampbell** [comment]
I guess the question is do we want to know an exception saying already cancelled, or do we want to do nothing. The same applies for the other functions.

**Comment by driesvints** [comment]
Pushed a fix for this.
