### ISSUE TITLE
`handleSubscriptionUpdated` references an undocumented field

### ISSUE THREAD

**Issue by queicherius** [laravel/cashier-paddle#41]
### Description:

https://github.com/laravel/cashier-paddle/blob/a029d2ba89cf6132b4a554bb7de8285258b2e4f0/src/Http/Controllers/WebhookController.php#L161-L164

According to the Paddle documentation, `quantity` does not exist on the [subscription updated](https://developer.paddle.com/webhook-reference/subscription-alerts/subscription-updated) event, instead there are `new_quantity` and `old_quantity`.

### Steps To Reproduce:

:warning: I was just checking against the documentation / the webhook alert test. I'm not actually running Cashier, just using it as a reference for implementation in a different language.

**Comment by queicherius** [comment]
An additional question, if you are okay answering it:

In `handleSubscriptionCancelled`, if `cancellation_effective_date` is set, but not truthy, it is assumed to not to be cancelled. Can it actually happen that the webhook is called with this date set to a non-truthy value (or without the date at all)?

**Comment by driesvints** [comment]
Good spot thanks! Sent in a PR here: https://github.com/laravel/cashier-paddle/pull/44

The `cancellation_effective_date` is indeed always set. This was a legacy piece from the Cashier Stripe package where everything happens in the `subscription.updated` webhook.
