### ISSUE TITLE
Page Not Found Sorry, the page you were looking for could not be found.

### ISSUE THREAD

**Issue by FreddyCrugger** [laravel/cashier-paddle#47]
Hello,

I am trying to create a fake purchase and have a few questions please.

1)When the amount if below 0.75 Euro, I get the error (The price is too low), is this normal?

2)When I use the belowcode:

```
  $user = User::find(Auth::id());
        $payLink = $user->charge(0.75, 'test onecharge');

        return view('home', ['payLink' => $payLink]);
```

I see a green button on my front end, click on it but get this message:
![image1](https://user-images.githubusercontent.com/6231274/88838171-72104a00-d1d9-11ea-82b3-9fd466c1c7e3.jpg)

I thought this code could be used to create 1 time charge from the back end(without firs inputting the product name in the paddle admin panel.

Any idea why this is happening please?

Thank you.

**Comment by GrahamCampbell** [comment]
> When the amount if below 0.75 Euro, I get the error (The price is too low), is this normal?

Yes, you cannot charge someone such a small amount. If you need to charge customers lots of small amounts, you should batch up the charges, and charge them all together.

**Comment by GrahamCampbell** [comment]
> I am trying to create a fake purchase and have a few questions please.

What do you mean, fake purchase? Paddle currently doesn't support test purchases. You must use a real card and make a live transaction, or use a 100% off discount code. If you have tried to enable the test mode config option, that would explain the 404s.

**Comment by FreddyCrugger** [comment]
Sorry, my apology, by fake purchase I meant "purchased done from my side to test the system". Yes I understand that they have no system in place to create a fake purchase(I was surprised to be honest). The 100% off coupon is a great Idea I did not know about it.

So based on this code:

```
 $user = User::find(Auth::id());
        $payLink = $user->charge(0.75, 'test onecharge');

        return view('home', ['payLink' => $payLink]);
```
 
Do I have to create the "test onecharge" product in my paddle account first? As this is not explained in the doc.
It says simple one time charge.

I was hoping to be able to see the checkout with the above code.


Thank you.

**Comment by GrahamCampbell** [comment]
> Do I have to create the "test onecharge" product in my paddle account first?

Yes, I think so. Note that product IDs are integers, not strings.

**Comment by FreddyCrugger** [comment]
Thanks, let me try that.

**Comment by FreddyCrugger** [comment]
Just to let you know, in your doc you show a string.

**Comment by FreddyCrugger** [comment]
I havet tried both as a string and integer, I get the same error for the simple charge. I have create the product and/or subscription in the paddle back end but it is not working.

**Comment by GrahamCampbell** [comment]
Paddle will tell you the product ID. It's not something you are able to choose.

**Comment by FreddyCrugger** [comment]
Yes I know, I create them in the paddle back end:
product id: 596697
Subscription plan: 596246

But none of them work with the simple product, but they work with this code:
```
$user = User::find(1);

$payLink = $user->newSubscription('default', $premium = 34567)
    ->returnTo(route('home'))
    ->create();

return view('billing', ['payLink' => $payLink]);
```

Thank you.

**Comment by Hussam3bd** [comment]
@FreddyCrugger
Just make sure to add `CASHIER_WEBHOOK` in your .env file, the webhook URL is required by Paddle when you create a charge.

**Comment by Hussam3bd** [comment]
@FreddyCrugger Also for the price Paddle required a minimum amount to charge it was around $0.90, I'm not sure how much it was but you can try to create a product and play around it.

**Comment by FreddyCrugger** [comment]
Thanks, this must be the problem then.

In the doc it says:

To ensure your application can handle Paddle webhooks, be sure to configure the webhook URL in the Paddle control panel. By default, Cashier's webhook controller listens to the /paddle/webhook URL path. The full list of all webhooks you should configure in the Paddle control panel are:

Subscription Created
Subscription Updated
Subscription Deleted
Payment Succeeded
Subscription Payment Succeeded

I did not look into this because the simple charge was not mentioned there.

**Comment by Hussam3bd** [comment]
@FreddyCrugger 
Your welcome hope it solved your problem,

I think when you charge user things work differently, casher will send a request to Paddle to create pay link and Paddle in this case as the product id is not set will ask for the webhook URL and return URL.

But when you create a subscription you set Paddle's product id and the webhook URL is not required in this case
and Paddle will check if you provide webhook ULR in the vendor's dashboard.

**Comment by FreddyCrugger** [comment]
Thanks great explanation. I will have to try it tomorrow night, 1am here :-(

Thanks again and I will revert back if it does not work.

**Comment by driesvints** [comment]
> The 100% off coupon is a great Idea I did not know about it.

Please read the docs: https://laravel.com/docs/7.x/cashier-paddle#testing

<img width="776" alt="Screenshot 2020-07-30 at 13 56 35" src="https://user-images.githubusercontent.com/594614/88920089-88b3b100-d26c-11ea-8190-8ec3b47b6ca0.png">

> Do I have to create the "test onecharge" product in my paddle account first? As this is not explained in the doc.
It says simple one time charge.

Again, explained here: https://laravel.com/docs/7.x/cashier-paddle#single-charges. Both simple charges and product charges are explained here.

> Just to let you know, in your doc you show a string.

It does not? Please show where you see that. I've spotted one string usage in the subscription docs but all the others use an integer. I'll update that specific example.

> I did not look into this because the simple charge was not mentioned there.

The very first step in the installation section says:

<img width="732" alt="Screenshot 2020-07-30 at 14 00 43" src="https://user-images.githubusercontent.com/594614/88920427-214a3100-d26d-11ea-8997-c253e552db87.png">

Honestly, I don't mind helping out but you've clearly not read the docs closely enough. I'm going to close this now as the issue tracker isn't a support channel but if you try the `cashier-paddle` channel on Discord I'll try to help you out further.

**Comment by FreddyCrugger** [comment]
Why did you add any comments? Hussam3bd sorted it all for me?
