### ISSUE TITLE
Issue with models other than User

### ISSUE THREAD

**Issue by enkota** [laravel/cashier-paddle#5]
Hi,

Thanks for creating this package! Hoping to test this out on my next app.

I've discovered a couple small issues so far.

1. When creating the migration files it seems to still use the `stripe_id` etc instead of the one's made automatically by this package.

2. If using another Model for Billable, when I try to go create a `payLink` it will return the following error (seems like it's trying to check the auth user?) This could be related to a multi-tenancy package I'm using but seems to work fine if using the normal `User` model.

Thanks!

**Code:**
`$tenant->newSubscription('default', '123456')->returnTo(route('home'))->create();`

**Error:**
`Call to undefined method App\Tenant::getAuthIdentifier()`

**Comment by driesvints** [comment]
Heya, thanks for testing out! The auth idenfitier issue has already been resolved by https://github.com/laravel/cashier-paddle/pull/3 and will be in the next beta tag.

> When creating the migration files it seems to still use the stripe_id etc instead of the one's made automatically by this package.

There's no reference to stripe_id anywhere here in this package. Are you sure you're looking at the correct code? If there's a `stripe_id` reference then it's somewhere in your own app.

**Comment by driesvints** [comment]
You can use dev-master for now to work around the auth identifier issue btw.

**Comment by enkota** [comment]
Hey @driesvints thanks for the speedy response!

Ahh it must have conflicted with a previous version of stripe cashier. Will check see what’s causing that. 

That’s great, will go try the dev build!
