### ISSUE TITLE
Expose payment method

### ISSUE THREAD

**Issue by egoist** [laravel/cashier-paddle#51]
Subscription methods like `cardBrand` are only available when the payment method is credit card, it makes sense to check payment method before accessing it, currently I can get the payment method via `$subscription->paddleInfo()['payment_information']['payment_method']` but it's not documented, maybe it's better to expose it as `$subscription->paymentMethod()` too.

**Comment by driesvints** [comment]
Done: https://github.com/laravel/cashier-paddle/commit/6f78dfe10a4fcb3033591385a1f20eb16412a8b7
