### ISSUE TITLE
allowQuantity set to False not working

### ISSUE THREAD

**Issue by FreddyCrugger** [laravel/cashier-paddle#52]
```
### Versions
        "php": "^7.4",
        "laravel/cashier-paddle": "^1.0.0-beta.2",
        "laravel/framework": "^7.24.0",
```

### Description:
Unable to add a custom parameter called 'allowQuantity' => 'false' with the chargeProduct() method.
When set to false, the quantity in the popup is still visible.

### Steps To Reproduce:

```
       $payLink = $user->chargeProduct('111111', [
       'allowQuantity' => 'false',
]);

        return view('view', ['payLink' => $payLink]);

```

To test if custom parameters are working I tried:

```
       $payLink = $user->chargeProduct('111111', [
       'quantity' => 1,
]);
```

And the above worked.
I followed the Paddle parameters from here:
[](https://developer.paddle.com/reference/paddle-js/parameters)

Thank you.

ps: obviously the 11111 has been replaced but I was using a working product integer from my Paddle admin panel

**Comment by driesvints** [comment]
The paylink API has no such option: https://developer.paddle.com/api-reference/product-api/pay-links/createpaylink
