### ISSUE TITLE
Unknown column 'subscriptions.billable_id' after upgrading the laravel framework and paddle.

### ISSUE THREAD

**Issue by dlogvin** [laravel/cashier-paddle#56]
- Cashier Paddle Version: ^1.0@beta (v1.0.0-beta2)
- Laravel Version: 7.25.0
- PHP Version: ^7.2.5
- Database Driver & Version: mysql

### Description:

After a `composer update`, and running the migrations, the column went missing.

In my code I'm trying to do the following: 

`@if(Auth::user()->subscribedToPlan($monthly = 123123, 'Service Pro'))`

**Comment by GrahamCampbell** [comment]
After upgrading from what?

**Comment by dlogvin** [comment]
I mean, I just did a composer update. Laravel was upgraded, as well as paddle.

**Comment by GrahamCampbell** [comment]
Yes, from what versions? NB There is no upgrading path from earlier paddle versions to newer betas. You will need to either throw away your data, or migrate it manually yourself. Once a stable release is available, then upgrade paths will be available.

**Comment by GrahamCampbell** [comment]
I cannot stress enough that this package is not ready for production use yet, as per the documentation.

**Comment by dlogvin** [comment]
How so? As far as I know Paddle was upgraded to beta-2. The first version worked "fine". Not sure why the column suddently disappeared. You mean here that I should manually add that column?

**Comment by GrahamCampbell** [comment]
No, I mean the database structure has fundamentally changed since beta-1. https://github.com/laravel/cashier-paddle/commit/349f6615818135e5f76c51ee003f444f96031c0f

**Comment by dlogvin** [comment]
Understood. But what should I do now to solve this error message I'm getting?

**Comment by GrahamCampbell** [comment]
Drop your database, and re-migrate with the latest migrations from the package. If you have published stuff from the package, delete it and re-publish it.

**Comment by GrahamCampbell** [comment]
Usage with your user model may also have changed. Check the current version of the docs.

**Comment by dlogvin** [comment]
Sure, will try it out. Will update on this :)

**Comment by dlogvin** [comment]
tried that, same thing happening.

**Comment by dlogvin** [comment]
Alright, I noticed something. 92cc974 made a change, and I had 2 migrations, one labelled customers and another one customer.

The conflict was caused because it was renamed, resulting for my app to generate 2 different tables. Not sure how to use the other one after deleting the old one.

**Comment by dlogvin** [comment]
Solved now after copying and pasting the migration from the repo (https://github.com/laravel/cashier-paddle/blob/92cc974477e2ec52af480492bd4695b7ff3855c4/database/migrations/2019_05_03_000002_create_subscriptions_table.php).
