### ISSUE TITLE
View is not found in production (I know, this should not be used in production).

### ISSUE THREAD

**Issue by dlogvin** [laravel/cashier-paddle#57]
- Cashier Paddle Version: ^1.0@beta (v1.0.0-beta2)
- Laravel Version: 7.25.0
- PHP Version: ^7.2.5
- Database Driver & Version: mysql

### Description:

I know this shouldn't be used in production, still, I really have no other option than giving it a try. In my country, paddle seems to be the best and only solution.

### Steps To Reproduce:

well, my view (blade, by the way) is indeed loaded in the localhost (homestead), but not in the production server.

**Comment by driesvints** [comment]
Heya. What view? Have you tried running `a view:clear`? Have you tried this on a fresh app?

**Comment by dlogvin** [comment]
Hey! Yes, I tried `view:clear`. It is my `billing` view, where I included the widget. 

This is the code block that seems to be causing the trouble:

```
                                @if(Auth::user()->subscribedToPlan($monthly = 123123, 'Pro'))
                                <div>
                                    <a class="btn btn-outline-success">Current plan ✨ </a>
                                </div>
                                @else
                                <div>
                                    <x-paddle-button :url="$payLink" class="px-8 py-4" data-theme="none" class="btn btn-primary">
									    Go premium! 🚀
									</x-paddle-button>
                                </div>
                                @endif
```

**Comment by driesvints** [comment]
What's the exact error you're getting?

**Comment by dlogvin** [comment]
`[2020-08-16 11:42:00] production.ERROR: View [dashboard.settings.billing] not found. {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): View [dashboard.settings.billing] not found. at /home/forge/hwrk.app/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)
[stacktrace]`

**Comment by driesvints** [comment]
That doesn't seems to have anything to do with Cashier Paddle. Your view simply doesn't exists on your production server.

**Comment by dlogvin** [comment]
You sure it doesn't? 

```
root@App:/home/forge/appname/resources/views# cd dashboard/

root@App:/home/forge/appname/resources/views/dashboard# ls
Settings 
dashboard.blade.php      settings.blade.php

root@App:/home/forge/appname/resources/views/dashboard# cd Settings/

root@App:/home/forge/appname/resources/views/dashboard/Settings# ls

billing.blade.php  subscriptionHistory.blade.php  theme.blade.php

```

subscriptionHistory does load, theme does load too.

**Comment by driesvints** [comment]
Yes

**Comment by dlogvin** [comment]
I just showed you that it exists... it loads in localhost too. The folder and file structure is absolutely the same

**Comment by dlogvin** [comment]
oof, it was a typo. My bad, my bad. it had to be "S", not "s". lol, so sorry to trouble you.
