### ISSUE TITLE
Can we use it in production?

### ISSUE THREAD

**Issue by FreddyCrugger** [laravel/cashier-paddle#6]
Hello!,

Thanks for this superb package, I cannot wait to install it on my Laravel 7 app.
Is it safe to use in production? If not, when do you think it will be safe enough for a launch?

Thank you so much,

**Comment by driesvints** [comment]
Heya, please see the note in the readme and in the docs. While in beta we don't recommend shipping to production. Atm we don't have a launch date. The more people help test the beta, the faster we can release a stable version.

**Comment by FreddyCrugger** [comment]
Ok thanks, started the integration last night, will go through everything daily as I am also in contact with Paddle via email. Will log in any bugs I may encounter on Git don't worry.
