### ISSUE TITLE
Improving contributing guide

### ISSUE THREAD

**Issue by yoeriboven** [laravel/cashier-paddle#60]
The [contributing guide](https://github.com/laravel/cashier-paddle/blob/master/.github/CONTRIBUTING.md) is not clear in what is needed to setup the project.

It seems like you need to add your Paddle API keys, but some more information would be appreciated. 

Currently can't get tests to green on my machine because I'm missing variables and the correct setup.

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/cashier-paddle/pull/65
