### ISSUE TITLE
Paddle Subscription Modifiers

### ISSUE THREAD

**Issue by enkota** [laravel/cashier-paddle#71]
Hey,

Wondering if Paddles subscription modifiers exist within the package? Took a look at the docs, but only thing it mentions is [Subscription single charges](https://laravel.com/docs/7.x/cashier-paddle#subscription-single-charges) - is this referencing modifiers reference [here](https://developer.paddle.com/api-reference/subscription-api/modifiers/createmodifier)?

I am aiming to make use of this feature to be able to modify a users recurring subscription price and [metered billing](https://developer.paddle.com/guides/how-tos/subscriptions/metered-billing).

Cheers!

**Comment by enkota** [comment]
By no means great with PR's but I mocked up how this could be done by extending the subscription model.

From the API docs it seems we can't update existing modifiers, so I am wondering if the `modifier_id` returned should be stored on our DB so it can be deleted if the modifier was to change in the future. Only issue I see with that is you can have multiple modifiers per subscription.

```
    /**
    * Add a modifier to the Paddle plan.
    *
    * @param int $plan
    * @param array $options
    * @return $this
    */
    public function modifier($plan, array $options = [])
    {
       
         $payload = $this->billable->paddleOptions(array_merge([
         'subscription_id' => $this->paddle_id,
         'modifier_amount' => '10', //Would pass this via $options
         'recurring' => 1, //Probably make use of ->recurring();
         'modifier_description' => 'Added by Cashier'
         ], $options));
  
         $response = Cashier::post('/subscription/modifiers/create', $payload)['response'];

         $this->paddleInfo = null;

         return $response;
    }
```

**Comment by driesvints** [comment]
The reason we didn't include it in the package is because Paddle already has a full UI in their dashboard to manage these modifiers.

Can you please give some more explanation about your use case, why you'd want to use the API for these and how it would benefit you?

**Comment by enkota** [comment]
Hey @driesvints - The original idea was to make use of modifiers with volume based billing. Every level of usage would result in a price modifier being added so we didn't need to create loads of individual plans. I took the idea from [their guide](https://developer.paddle.com/guides/how-tos/subscriptions/metered-billing).

After a few discussions with Paddle, we decided modifiers would be too messy in the long run. I've setup new plans per (1000 contacts) on my app instead.

I can see some uses for it however if someone wanted to automate a modifier on an existing subscription, rather than their UI.

Happy to close this as ended up not using. For anyone that needs it, the code above should mostly work :)

**Comment by driesvints** [comment]
No worries. Closing then as there's no direct use case.

**Comment by pawan1793** [comment]
@driesvints  I might have use case ... 
Our subscription prices keeps on changing so can't keep adding new subscriptions in paddle instead of that if **modifier** is included in package we can **simply change recurring prices** 

reference[ /2.0/subscription/modifiers/create](https://developer.paddle.com/api-reference/subscription-api/modifiers/createmodifier)

**Comment by driesvints** [comment]
@pawan1793 what prevents you from using the Paddle dashboard?

**Comment by pawan1793** [comment]
@driesvints in paddle dashboard there is just one plan of $1 ... I'll be modifying plan pricing on my application not on paddle, This way I'll not have to maintain many subscription products.

eg There are 3 plans 
Basic - 5$
Gold - 10$
Pro - 15$

for all this plan i'll use subscription product i.e of $1 on paddle  and set prices while creating subscription by **Overriding Checkout Prices**

now if user want to change Gold plan. having modifier will help to  add amount on current subscription.

**Comment by driesvints** [comment]
If you can practically write down what you expect to be present in terms of a public API we could look into it maybe. Is it similar to what the OP wrote above?

**Comment by pawan1793** [comment]
yes

**Comment by driesvints** [comment]
I'll take a look at this eventually. But feel free to send in a PR in the meantime.

**Comment by yoeriboven** [comment]
@pawan1793 Isn't your issue the same as [this](https://github.com/laravel/cashier-paddle/issues/86)?

I agree that modifiers would be a great addition to this package but I don't think you need them.

**Comment by enkota** [comment]
I'd like to point out when I looked at this, Paddle didn't allow you to update modifiers, so you'd need to store the one applied to that subscription and remove if you were to change that amount.

**Comment by driesvints** [comment]
Yeah we'll need to do that as well.

**Comment by msnegurski** [comment]
Just to add a usecase: we have a non-linear per member pricing (so subscription quantity is not an option) and customers constantly add or remove members, so managing it all in the Dashboard would be a full-time job.

**Comment by driesvints** [comment]
This will be available in today's release. I'll try to add docs soon.
