### ISSUE TITLE
Eager loading not possible

### ISSUE THREAD

**Issue by yoeriboven** [laravel/cashier-paddle#73]
- Cashier Paddle Version: 1.2.0
- Laravel Version: 7.26.1
- PHP Version: 7.4.10
- Database Driver & Version: MySQL

### Description:
I'm accessing the user's subscription multiple times on my settings page. This results in a separate query for every access.

According to Laravel Debugbar I'm making the same subscriptions request nine times.

This is the culprit:

```php
$user->subscription('default')
```

How to eager load this query? Using `$with` on the `User` actually adds a query.

Part of this could also me not understanding something about relationships, but there's a case to be made that there shouldn't be a database query every time you use the `subscription()` function.

### Steps To Reproduce:
Run `$user->subscription()` multiple times.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by yoeriboven** [comment]
@driesvints Hi Dries.

I'm starting to think this is actually a package issue. 

The amount of duplicate queries drops from 8 to 0 when making the following change. ([line](https://github.com/laravel/cashier-paddle/blob/1.x/src/Concerns/ManagesSubscriptions.php#L40))

```php
$this->subscriptions()->where('name', $name)->first();
```
```php
$this->subscriptions->where('name', $name)->first();
```

This is also how it is done in the Stripe version of Cashier. ([line](https://github.com/laravel/cashier-stripe/blob/12.x/src/Concerns/ManagesSubscriptions.php#L95))

```php
/**
 * Get a subscription instance by name.
 *
 * @param  string  $name
 * @return \Laravel\Cashier\Subscription|null
 */
public function subscription($name = 'default')
{
    return $this->subscriptions->sortByDesc(function (Subscription $subscription) {
        return $subscription->created_at->getTimestamp();
    })->first(function (Subscription $subscription) use ($name) {
        return $subscription->name === $name;
    });
}
```

By using the function you always access the relationship and make a new query instead of accessing the previously loaded results.

Could you confirm this isn't a bug?

I took the liberty to create [a PR](https://github.com/laravel/cashier-paddle/pull/74) so this can quickly be resolved in case you agree with me.

**Comment by driesvints** [comment]
Hey Youri. Your change would load all subscriptions into memory and do the where clause on the collection rather than the query builder. This would raise its own sets of problems (see Taylor's response on your PR).

I think the code in Cashier Stripe is for legacy purposes but not entirely sure. I'm attempting a PR to simplify it in Cashier Stripe: https://github.com/laravel/cashier-stripe/pull/1002
