### ISSUE TITLE
Webhook error after creating subscription

### ISSUE THREAD

**Issue by ack202** [laravel/cashier-paddle#75]
- Cashier Paddle Version: 1.2
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: mySQL

### Description:
After subscribing to a subscription the received answer triggers the following error:

Trying to access array offset on value of type int {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type int at /home/forge/project/vendor/laravel/cashier-paddle/src/Http/Controllers/WebhookController.php:246)

Thats the following function, which seems to be correct:

```
    protected function findOrCreateCustomer(string $passthrough)
    {
        $passthrough = json_decode($passthrough, true);

        return Customer::firstOrCreate([
            'billable_id' => $passthrough['billable_id'],
            'billable_type' => $passthrough['billable_type'],
        ])->billable;
    }
```

**Comment by ack202** [comment]
This error only occurs if you create the paddle checkout link manually. I assume the passthrough parameters are different when using the cashier paylink.

**Comment by driesvints** [comment]
Yeah indeed. You should only use pay links with cashier paddle. Otherwise the required passthrough values are never sent. I've re-opened this so I can add this as a note to the docs and maybe check into throwing a more descriptive exception.

**Comment by GrahamCampbell** [comment]
Did you want the subscription to appear in your app or be skipped? If create it manually but don't pass through the cashier specific stuff, then the best we can do is ignore the subscription.
