### ISSUE TITLE
$user->subscribed('default') returns true no matter what.

### ISSUE THREAD

**Issue by FreddyCrugger** [laravel/cashier-paddle#79]
```
"require": {
        "php": "^7.3",
        "laravel/cashier-paddle": "^1.2",
        "laravel/framework": "^8.6.0",
    },
```

### Description:
I have cancelled 2 subscriptions from the only user I have on the system as you can see here from the Paddle callback:
![subscription](https://user-images.githubusercontent.com/6231274/94488387-d011db80-01e2-11eb-933f-56a540f49e7a.jpg)

Based on the documentation, I was expecting the result to return 'false':
https://laravel.com/docs/7.x/cashier-paddle#checking-subscription-status

### Steps To Reproduce:
```
    public function index()
    {
        $user = User::where('id',Auth::id())->first();  // Same as: firstWhere('id',Auth::id())
        if ($user->subscribed('default')) {
            logger('true');
        }else{
            logger('false');
        }
    }
```

I always get "true" in the logger even if the subscription status shows in the database "deleted"

Any idea why please?

Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lvismer** [comment]
@driesvints For me I also have a *deleted* subscription in my subscriptions table but a call to ```$user->subscriptions()->active()``` returns that subscription. I would have expected ```active()``` to only return a valid subscription. Does the implementation consider a *deleted* subscription still active?

**Comment by FreddyCrugger** [comment]
The problem is that some subscriptions in certain systems carries on after the cancellation while others need to be partially refunded(like in mine) or you get extra API call cost(or proxy usage and so on). In my case, the subscription when deleted,  if cannot be active. I had to modify the code for my case. This is why I was confused when I saw that a deleted subscription was still considered active.

**Comment by techguydev** [comment]
I am having the same problem, what is the best wat to go around with this ?

**Comment by FreddyCrugger** [comment]
This is how it works at the moment:
```
        if ($user->subscribed('default')) {
            logger('true');
        }else{
            logger('false');
        }
```

If the subscription has been cancelled, it will still return true until the date reaches the last day of the subscription(ends_at column). In your case, it is fine.

**Comment by driesvints** [comment]
Hey everyone. The reason why subscribed is returning true is that the subscription might be deleted but it's on its cancellation grace period (see the date in the "ends_at" column). 

If you want to immediately cancel a subscription you need to use `->cancelNow`. See the docs here: https://laravel.com/docs/8.x/cashier-paddle#cancelling-subscriptions

**Comment by driesvints** [comment]
This is also the same reason why the `active` scope still returns the subscription. It's still an active subscription until its grace period has passed. This works the same in Cashier Stripe.

**Comment by Maarondesigns** [comment]
Thanks @driesvints! I was having the same problem and that solved it for me. 

I had a subscription that was canceled in Stripe and the webhook didn't update the subscription on my local dev environment, so I manually updated the `stripe_status` field to "canceled" and was really frustrated why `$user->subscription('default')->ended()` and `$user->subscription('default')->canceled()` were both still returning `false`. I guess the `ends_at` field is really the only one that matters. The `stripe_status` is really just a user friendly string in case you want to display it to the end user.
