### ISSUE TITLE
1 Month subscription save the ends_at date - 3 months subscription ends_at missing

### ISSUE THREAD

**Issue by FreddyCrugger** [laravel/cashier-paddle#80]
![save](https://user-images.githubusercontent.com/6231274/94669274-4d3b6e80-0311-11eb-84ff-f4e6dc95a5ce.jpg)
```
        "php": "^7.3",
        "ext-dom": "*",
        "laravel/cashier-paddle": "^1.2",
        "laravel/framework": "^8.6.0",
```

I have created in Paddle 2 subscriptions.
1 set with a 1-month billing interval.
1 set with a 3 months billing interval.

When the transactions happen, the webhook call back from Paddle is sent correctly to the Paddle Laravel callback URL on my website. The "next_bill_date" in the json response shows with the first subscription a 1-month billing interval while with the other subscription a 3 months billing interval, all good.

The problem happens in the database table called "subscriptions".

On a 1 month subscription, the "ends_at" column is filled in with the correct 1-month billing interval.
On a 3 months subscription, the "ends_at" column stays as null.

I have repeated the process again and again with no luck.

Thank you.

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.

**Comment by FreddyCrugger** [comment]
I am not understanding

**Comment by driesvints** [comment]
https://github.com/laravel/cashier-paddle/issues/new?template=1_Bug_report.md

![Screenshot 2020-10-01 at 15 10 24](https://user-images.githubusercontent.com/594614/94813423-40457a80-03f8-11eb-94f4-3a22ef953688.png)

**Comment by FreddyCrugger** [comment]
"php": "^7.3",
        "ext-dom": "*",
        "laravel/cashier-paddle": "^1.2",
        "laravel/framework": "^8.6.0",
        Database client version: libmysql - 5.6.43


###description
When a subscription is created in Paddle with a billing interval of 1 month, the ends_at column is filled with the right date.
When a subscription is created in Paddle with a billing interval of 3 months, the ends_at column shows as NULL.

Paddle example of a 3 months subscription.
![94669274-4d3b6e80-0311-11eb-84ff-f4e6dc95a5ce](https://user-images.githubusercontent.com/6231274/94814805-12f9cc00-03fa-11eb-899e-7c1e5f722254.jpg)



###steps
Create in Paddle:
A 1-month SUBSCRIPTION billing interval.
A 3-months SUBSCRIPTION billing interval.

Pass the transaction and wait for the webhook from Paddle to update the database columns to see the issue with the ends_at column.

**Comment by driesvints** [comment]
Please open a new issue with the issue template and don't copy paste your composer.json file. Use the versions from your composer.lock file
