### ISSUE TITLE
SubscriptionBuilder missing custom pricing  payloads i.e Overriding Checkout Prices

### ISSUE THREAD

**Issue by pawan1793** [laravel/cashier-paddle#86]
Paddle supports **Overriding Checkout Prices**  this helps to customise recurring charges and avoids relying on paddle product data for prices,passing in prices to override the initial checkout price or recurring_prices if you wish to override a subscription’s subsequent recurring payment amount

Read more here 
[https://developer.paddle.com/guides/how-tos/pricing/override-checkout-prices#overriding-checkout-prices](https://developer.paddle.com/guides/how-tos/pricing/override-checkout-prices#overriding-checkout-prices)

**Comment by yoeriboven** [comment]
Haven't tested this but can't you pass the prices to the `create` method on `SubscriptionBuilder`?

```php
$payLink = $user->newSubscription('default', $premium = 12345)
    ->returnTo(route('home'))
    ->create([
    'prices' => [
        "USD:19.99",
        "EUR:15.99"
    ]
]);
```

There are [some concerns](https://github.com/laravel/cashier-paddle/blob/1.x/src/SubscriptionBuilder.php#L172) if you are also using a trial so you need to take that in account.

**Comment by pawan1793** [comment]
Sorry my bad ... just tested it's working after passing parameter in create method
