### ISSUE TITLE
New method to end a subscription for testing purposes

### ISSUE THREAD

**Issue by FreddyCrugger** [laravel/cashier-paddle#88]
Hello,

I was trying to test this:
```
if ($user->subscription('default')->ended();) {
    //
}
```

I was unable to create a fake "end" to the subscription.
I tried to change the paid_at date, updated_at, created_at in both the subscriptions and receipts tables but no luck.

Would it be possible to have a function where the tester can fake an end to a subscription please(not a cancellation but actual end)?

Thank you

**Comment by driesvints** [comment]
Fill out the `ends_at` column on the subscription with a date in the past.

**Comment by FreddyCrugger** [comment]
Oh i see, it would have been great to have this tiny part in the doc please.

Thanks.

**Comment by driesvints** [comment]
Feel free to send in a PR if you feel anything can be improved 👍
