### ISSUE TITLE
Publish blade file for button component

### ISSUE THREAD

**Issue by enkota** [laravel/cashier-paddle#9]
Couldn't see in docs if this is available, but would be good to allow users to publish the `x-paddle-button` component so we can override the default green styling better.

**Comment by enkota** [comment]
Looks like `data-theme="none"` solves this.

```
<x-paddle-button :url="$payLink" class="btn btn-primary" data-theme="none">
     Subscribe
</x-paddle-button>
```

**Comment by AbdelilahLbardi** [comment]
@enkota You can override cashier button component after publishing the views by doing the following command `php artisan vendor:publish --tag cashier-views`

**Comment by driesvints** [comment]
I left it like this because some people maybe want to use the default green. You can indeed use ` data-theme="none"` to remove any default Paddle styling. I'll document this.
