### ISSUE TITLE
Cancel subscription immediately works incorrectly?

### ISSUE THREAD

**Issue by victor-ponamariov** [laravel/cashier-paddle#92]
- Cashier Paddle Version: 1.2.3
- Laravel Version: 7.16.1
- PHP Version: 7.2
- Database Driver & Version: MySQL 8

### Description:

Not sure if it's a bug or not.

When I use `cancelNow()` method it should cancel the subscription immediately. What happens:

```
    /**
     * Cancel the subscription immediately.
     *
     * @return $this
     */
    public function cancelNow()
    {
        $payload = $this->billable->paddleOptions([
            'subscription_id' => $this->paddle_id,
        ]);

        // Here Laravel sends the request to Paddle
        Cashier::post('/subscription/users_cancel', $payload);

       // Here Laravel sets ends_at to the current date, immediately, and the subscription should be considered cancelled.
        $this->forceFill([
            'paddle_status' => self::STATUS_DELETED,
            'ends_at' => Carbon::now(),
        ])->save();

        $this->paddleInfo = null;

        return $this;
    }

```

However, then Paddle makes a webhook, notifying that the subscription has been cancelled. It also sends `cancellation_effective_date` which is used, as I get it, for grace period. Even though the subscription is cancelled right away (on the Paddle side), Paddle still sends the effective date.

And here how Cashier handles the webhook:

```
        $subscription->ends_at = $subscription->onTrial()
            ? $subscription->trial_ends_at
            : Carbon::createFromFormat('Y-m-d', $payload['cancellation_effective_date'], 'UTC')->startOfDay();
```

The subscription is not on trial => setup ends_at to the cancellation_effective_date.

For example, In the case of monthly subscriptions, the ends_at will be equal the current date + 30 days. And the subscription will be considered valid.

Then I don't get what's the difference between cancel and cancelNow, and why in the current logic it happens that end_at being rewritten twice: once to the current date, the second time to the effective date.

**Comment by driesvints** [comment]
Heya, thanks for this detailed report. This indeed looks like a bug to me. I'll try to look into fixing this soon.

**Comment by driesvints** [comment]
I've finally managed to find time to send in a fix for this: https://github.com/laravel/cashier-paddle/pull/99
