### ISSUE TITLE
Getting  SubscriptionPaymentFailed not found on log

### ISSUE THREAD

**Issue by techguydev** [laravel/cashier-paddle#93]
- Cashier Paddle Version: v1.2.0
- Laravel Version:7.16.1
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:

I keep getting " Class 'Laravel\Paddle\Http\Controllers\SubscriptionPaymentFailed' not found " error on my logs, it looks like paddle is making a post request to my system and not finding that to do next.

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest version of the package. This issue has already been fixed.

**Comment by driesvints** [comment]
See above
